### ISSUE TITLE
Set AC State API Endpoint

### ISSUE THREAD

**Issue by aesign** [h4de5/home-assistant-toshiba_ac#1]
Hello there! I was wondering if you found the api endpoint to just set ACs on/off. E.g. a POST to something like `api/AC/SetACState`. Thank you for your work.

**Comment by h4de5** [comment]
this - hopefully - will be available through the save scheduler endpoint. but i so far i could successfully test it.

**Comment by aesign** [comment]
Great! Would you be so kind to share a sample of request body I need to POST to toggle an AC on/off?

**Comment by h4de5** [comment]
well - this is part of the task I am working on currently :)

basicaly - after you get your consumer and ACid through the mapping call (/api/AC/GetConsumerACMapping) you send an update to /api/AC/SaveACProgramSetting with a program starting in one minute in the future like this:

```json
{
  "ConsumerId": "xxxx",
  "MeritFeature": "0000",
  "ACId": "xxxx",
  "ACUniqueId": "xxxx",
  "ACName": "Klima",
  "ACModel": "1",
  "timeZone": "W. Europe Standard Time",
  "ACStateDataForProgram": "31xxxxx",
  "schedulerStatus": "01",
  "dst": {
    "Time": "1635649200",
    "Status": "OFF"
  },
  "programSetting": {
    "Sunday": {
      "p1": "",
      "p2": "",
      "p3": "",
      "p4": ""
    },
    "Monday": {
      "p1": "",
      "p2": "",
      "p3": "",
      "p4": ""
    },
    "Tuesday": {
      "p1": "",
      "p2": "",
      "p3": "",
      "p4": ""
    },
    "Wednesday": {
      "p1": "200030421832ff41",
      "p2": "213031ffffffffff",
      "p3": "",
      "p4": ""
    },
    "Thursday": {
      "p1": "",
      "p2": "",
      "p3": "",
      "p4": ""
    },
    "Friday": {
      "p1": "",
      "p2": "",
      "p3": "",
      "p4": ""
    },
    "Saturday": {
      "p1": "",
      "p2": "",
      "p3": "",
      "p4": ""
    }
  }
}
```

**Comment by h4de5** [comment]
I added some more example code. it is possible to update the schedule now. (Beware: the example code will reset the program for the current day, activate all ACs for 5 minutes and turn them off again afterwards).
the program is also shown within the app - but, at least mine, is not turned on.

**Comment by aesign** [comment]
Thank you! I highly appreciate the work you've been doing. I find absolutely weird that there's not a way to send an instant on/off command by the way... 

Another curious thing is that when I tried  to monitor Toshiba Home AC Control App's requests using Charles Proxy nothing showed up (I'm not an expert developer).

**Comment by h4de5** [comment]
the direct commands are sent in binary over a mqtt variant, which i could not recreate yet. see the link to the home-assistant forum for more information on that.

**Comment by Michael0yodi** [comment]
have you already done some work on investigating the binary string?

**Comment by h4de5** [comment]
no. I have given up that path. you can read about my findings to far here: https://community.home-assistant.io/t/toshiba-home-ac-control/137698/17

my issue was with the used protocol (amqp) and the way the implementation is somehow "obfuscated" in the azure libraries used in the app. 

a good starting point for understanding how it should work can be found in the docs:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-amqp-support
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response

unfortunatelly I do not have any other service I could possible test a self-written client with. if somebody can provider a python amqp client that does work with an azure web service, I can help providing the parameters which I found in the app.

the current state regarding the "scheduler path": I can update the program scheduler for the AC, but for some reasons it does not get activated at those planned dates. so I am kind of stuck here.

**Comment by h4de5** [comment]
with the help from @KaSroka it is now possible to send amqp requests and control the AC unit from within home-assistant.

download the repository, extract the custom_components directory in your home-assistant config folder and restart HA.
if everything works fine, the toshiba AC integration should show up in the Add Integration dialog. all you need is your username and password for your toshiba account - similar to the one on your mobile app.
it does have a few issues (see: https://community.home-assistant.io/t/toshiba-home-ac-control/137698/45?u=h4de5) at the moment - but basic control without any additional hardware is possible already
