### ISSUE TITLE
Feature: provide an additional service to set merit and special features like air_pure_ion

### ISSUE THREAD

**Issue by h4de5** [h4de5/home-assistant-toshiba_ac#10]
while the climate entity is currently maxed out in terms of functionality, any additional functions on the API could be implemented using a service.

those functions are:

- set_ac_air_pure_ion
- set_ac_merit_a_feature
- set_ac_merit_b_feature

**Comment by operinko** [comment]
What's the status of this? I would *really* love to be able to toggle *at least* the HEATING_8C merit_a feature on demand.  
I usually keep my garage AC at 12C upkeep with HEATING_8C enabled, but it would be useful to be able to turn that off for some "proper" heating temporarily after I drive my super-snowy car in there.

Workflow that I'm thinking of is something like:
Humidity has risen in the room, turn off HEATING_8C and set temp target to 22C, fans full speed.
Once humidity is back to normal levels, turn HEATING_8C back on and set temp target to 12C.

**Comment by h4de5** [comment]
pull requests are welcome

**Comment by jpeltoniemi** [comment]
Just FYI. I *might* take a stab at this during holidays. I really need to be able to control the fireplace mode of my Premium+ via automation.

No promises yet though. I don't know at all what I'm getting into and I don't have time to do extensive troubleshooting for other devices. If I manage to make something useful for myself, I'll share the code, but do hold your expectations :)

Meanwhile, any information about the related API is welcome.

**Comment by h4de5** [comment]
the existing PR is quite old and my no longer be compatible with HA standards (or the current main branch)

i think the API should be able to handle requests: https://github.com/KaSroka/Toshiba-AC-control

unfortunatelly I can't really test new stuff on my side, as the AC is shutdown during the winter. going to wake it up somewhere around april or may again ;)

**Comment by jpeltoniemi** [comment]
Thanks for the reply. If I manage to do anything useful, I'll provide any test results in as much detail as possible. I'll also try to keep in mind that different devices have different feature sets. My plan is to add support for the features my heat pump has but also keep the code extensible.

We'll have to see how it all goes - I have almost zero experience with python, but I'm hoping years of js and a lot of stubbornness are enough to compensate :)

**Comment by cmderks93** [comment]
Hi,
Any updates on this one? Really like if I can use the merit functions.

**Comment by jpeltoniemi** [comment]
Nothing, sorry. Been busy/lazy during the holidays. I really need the feature so this is definitely still on my todo list. It may take some time but whenever I get to it, I'll be sure to post updates here.

**Comment by PalmSwe** [comment]
Got a new AC unit, a Toshiba and using the integration, but also wishing there were a way to change merit_a_feature so I can have HEATING_8C turned on/off.

**Comment by juliekoubova** [comment]
I don't think a custom service is the most Home Assistant-y way to model this. I wrote #121 that adds an air purifier switch for each device that supports it. Adding all the other features in a similar way should be pretty straightforward, the API library already supports them.

**Comment by juliekoubova** [comment]
@PalmSwe you can try this branch if you'd like, it adds the 8 °C mode switch: https://github.com/juliekoubova/home-assistant-toshiba_ac/tree/fireplace

![image](https://user-images.githubusercontent.com/142506/235375341-8c84b682-dae4-41b1-bb91-a032fb8272df.png)
