### ISSUE TITLE
Frost-free value?

### ISSUE THREAD

**Issue by mycanaletto** [h4de5/home-assistant-toshiba_ac#108]
Hi,

It seems that in heating mode, the set temperature cannot be lowered below 17°.

How can I get a frost-free value?

Thanks

**Comment by tetienne** [comment]
Hi, can you set a value below 17 on the official Toshiba application?

**Comment by Claus65** [comment]
Original Toshiba App has a Button "ECO" with + 8°C Modus.

**Comment by mycanaletto** [comment]
> Hi, can you set a value below 17 on the official Toshiba application?

17° of course...

**Comment by Claus65** [comment]
> > Hi, can you set a value below 17 on the official Toshiba application?
> 
> 17° of course...

No, it is  not possible.  Only the Button ECO set the Temp to 8°C  this value is fix and not variable.

**Comment by mycanaletto** [comment]
And it is not possible to display this button in Home Assistant?

**Comment by tetienne** [comment]
It seems indeed to be possible, IMO we should use the preset features of the climate entity. 
I will try to implement it with other available features like BOOST

**Comment by h4de5** [comment]
check out the latest release. the device now has a separate switch for that.

**Comment by mycanaletto** [comment]
Thank you for these improvements!

In my house the 8° mode shows 4°.

![image](https://github.com/h4de5/home-assistant-toshiba_ac/assets/45459269/72f73cff-12b8-4add-945d-5f00294cf478)
