### ISSUE TITLE
Target temp (and fan & swing modes) not available when creating automations..!

### ISSUE THREAD

**Issue by pjylkka** [h4de5/home-assistant-toshiba_ac#109]
There's only HVAC mode & Preset available there.
Changing target temperature would be really nice to have too for overheating on low nordpool rates.
Am I doing something wrong or are these not implemented?

Please please pretty please  (insert puss in boots adorable stare here) <3

**Comment by tetienne** [comment]
Hi, in your automation, I guess you selected a device and not a service as action. 
If you call the service `climate.set_temperature` you will be able to perform what you want.

**Comment by pjylkka** [comment]
I see..! Thanks for the tip, I'll gonna check that out immediatly <3

**Comment by pjylkka** [comment]
> Hi, in your automation, I guess you selected a device and not a service as action. If you call the service `climate.set_temperature` you will be able to perform what you want.

This did the trick, closing this as solved, Thanks for the tip!
