### ISSUE TITLE
Is it possible to add energy consumption?

### ISSUE THREAD

**Issue by haseat** [h4de5/home-assistant-toshiba_ac#11]
Is it maybe possible to add a sensor for the energy consumption in kWh? This value is available in my Toshiba Home AC Control app, so maybe there is a way to include this for HA.

Thanks for the work you're doing, I really appreciate it!

**Comment by h4de5** [comment]
daily should be enough i think. HA would not be able to offer more detailed information for larger timespans.

**Comment by KaSroka** [comment]
I have added initial version to toshiba-ac 0.1.5. You can read the consumption with `ac_energy_consumption` device property. It will return object similar to this one: `ToshibaAcDeviceEnergyConsumption(energy_wh=19622, since='2020-12-31T23:00:00+00:00')` or `None` if energy reading is not available.

**Comment by h4de5** [comment]
for some reason `device.ac_energy_consumption` is never set.

**Comment by KaSroka** [comment]
I have it working now, will submit PR to feature branch in a minute.

**Comment by KaSroka** [comment]
It's working now. But it's impossible to add it to energy tab, just provides this link: https://www.home-assistant.io/more-info/statistics/ so something is wrong with how we provide this.

**Comment by KaSroka** [comment]
Ah, ok. Your porposal is based on `Entity` and not `SensorEntity`. Beside changes in PR i have released 0.1.8 which instead of `str` returns `datetime.datetime` which I have found is expected as `last_reset`.

**Comment by KaSroka** [comment]
They have introduced some changes in recent version: https://developers.home-assistant.io/blog/2021/08/16/state_class_total/

**Comment by h4de5** [comment]
sensor is now eligible for the energy dashboard. but - at least my device - is not showing any power consumption. not sure if my ac even has this feature tbh.

**Comment by haseat** [comment]
@h4de5 If you open the Toshiba Home AC Control app you should see "Energy Monitoring" in the bottom left corner. I can see the energy statistics for my AC there.

**Comment by KaSroka** [comment]
It's working for me, with just few changes (I'll add a PR for them):
![image](https://user-images.githubusercontent.com/9209665/131820689-8ace1440-e5cb-45d8-bd9e-39e7aca23838.png)

**Comment by KaSroka** [comment]
I have added #18, this works for me as shown in screenshot in previous comment.

**Comment by h4de5** [comment]
> @h4de5 If you open the Toshiba Home AC Control app you should see "Energy Monitoring" in the bottom left corner. I can see the energy statistics for my AC there.

I had to update the app, only than I got the notice about updating the firmware of the AC unit (to version 3.2). at least now I get a proper error message within the app, that energy consumption is not supported by my device.

so we may have to add that sensor based on a capability list - maybe we add those features to the attribute lists, so we can compare it. see: #9

**Comment by KaSroka** [comment]
Do you observe any other problems beside no energy consumption readout? If this is not breaking anything we may leave it for now (for unsupported devices the value will just be unknown)

**Comment by h4de5** [comment]
otherwise it seems fine. just I can't test it.

**Comment by h4de5** [comment]
should be done now.

please create a new issue if problems arise.
