### ISSUE TITLE
Automated set_fan_mode does not work

### ISSUE THREAD

**Issue by elsonico** [h4de5/home-assistant-toshiba_ac#112]
I can not climate.set_fan_mode working:

home-assistant.log:2023-02-23 09:22:00.003 INFO (MainThread) [custom_components.toshiba_ac.climate] Toshiba Climate setting fan_mode: LOW

The setting on internal unit stays auto:

home-assistant.log:2023-02-23 09:32:47.387 INFO (MainThread) [toshiba_ac.device] [AC_12494102] Current state: AcStatus: ON, AcMode: HEAT, AcTemperature: 20, AcFanMode: AUTO, AcSwingMode: SWING_VERTICAL, AcPowerSelection: POWER_100, AcFeatureMeritB: OFF, AcFeatureMeritA: OFF, AcAirPureIon: OFF, AcIndoorAcTemperature: 19, AcOutdoorAcTemperature: -5, AcSelfCleaning: OFF

I have tried with "Low", "low" and so on with no help. Same goes for  set_swing_mode. Everything works from Lovelace UI correctly as well setting scheduled automation for setting temperature.

**Comment by tetienne** [comment]
>  Everythng work from Lovelace UI correctly as well setting scheduled automation for setting temperature.

The setting of the fan mode through Lovelace works fine too?

**Comment by elsonico** [comment]
Yes, all the settings and their changing through lovelace works. On automation schedule (automation:) only on/off and chainging temperatore works. climate.set_swing_mode nor climate.set_fan_mode I have not been able to get to work.

**Comment by tetienne** [comment]
There is no specific code for lovelace or service. If you can correctly set the fan speed through lovelace, there is no reason it fails calling the service directly.

You can see the available values within the `Developper tools > States`. On my side, the values are: `Auto, Quiet, Low, Medium Low, Medium, Medium High, High
`

**Comment by elsonico** [comment]
Not sure if my problem was not using double quotation, but seems to work, when I copy the state from Developer tools as you suggested and put it between double quotes. Thank you for providing resolution. No reason for issue, since no with the code.
