### ISSUE TITLE
Setup failed for custom integration toshiba_ac: Requirements for toshiba_ac not found: ['toshiba-ac==0.3.1'].

### ISSUE THREAD

**Issue by Snapperud** [h4de5/home-assistant-toshiba_ac#113]
Use, HA ver Home Assistant 2023.3.0

Unable to install package toshiba-ac==0.3.1: ERROR: Cannot install toshiba-ac==0.3.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
Unable to install package toshiba-ac==0.3.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=60.0)")': /simple/toshiba-ac/ ERROR: Cannot install toshiba-ac==0.3.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by Kahera** [comment]
I get the above message in one log entry, as well as the following in another: 
```
Logger: homeassistant.setup
Source: setup.py:205
First occurred: 23:41:06 (1 occurrences)
Last logged: 23:41:06

Setup failed for custom integration toshiba_ac: Requirements for toshiba_ac not found: ['toshiba-ac==0.3.1'].
```

This started occurring after updating to 2023.3.0

**Comment by h4de5** [comment]
yep. same problem here. 
downside of using versions that just came out.

**Comment by boozeman** [comment]
Is there easy fix for this?

**Comment by jtosic** [comment]
Closed issue #99, once more @operinko to the rescue.

https://github.com/h4de5/home-assistant-toshiba_ac/issues/99#issuecomment-1442429277

**Comment by narfotic** [comment]
Same problem. Not working on newest version. Rolled back HA for now.

**Comment by udivankin** [comment]
@operinko  why not just leave `aiohttp>=3.8.1` in install_requires section there?

**Comment by operinko** [comment]
A fair point that I gave a bit of thought to. I'm not *too* comfortable with Python requirements format, and I didn't want to risk future aiohttp major version upgrade breaking things (3.x => 4.x) so I ended up limiting it.
I suppose I could bump it to 3.8.1 => 3.9.9 but that's still more risk of future breakage.

**Comment by udivankin** [comment]
@operinko To avoid forward compatibility with v4 when it comes out, I suggest using `'aiohttp>=3.8,<4'`. You can test it locally with e.g. `pip3 install 'aiohttp>=3.8,<4'`

**Comment by operinko** [comment]
Sure, but depending on how aiohttp implements semantic versioning, even 3.9.x might have major breaking changes.
I suppose I could do <3.9 but

**Comment by h4de5** [comment]
@KaSroka any chances for an update?

otherwise, @operinko if you give me the requirements line i have to change I can try to provide a beta version with your repo temporarily.

**Comment by operinko** [comment]
The line you'd need to change would be.. custom_components/toshiba_ac/manifest.json line 7.
From:
`"requirements": ["toshiba-ac==0.3.1"],`
To:
`"requirements": ["git+https://github.com/operinko/Toshiba-AC-control@0f1ef6f#toshiba-ac"],`

**Comment by blbeczech82** [comment]
> The line you'd need to change would be.. custom_components/toshiba_ac/manifest.json line 7. From: `"requirements": ["toshiba-ac==0.3.1"],` To: `"requirements": ["git+https://github.com/operinko/Toshiba-AC-control@0f1ef6f#toshiba-ac"],`

It works! Thank you...

**Comment by udivankin** [comment]
the above method didn't work, gave this error after adjusting requirements in manifest.json and trying to re-add an integration
<img width="538" alt="Screenshot 2023-03-02 at 23 57 51" src="https://user-images.githubusercontent.com/1522846/222567966-b64961da-0fa7-4045-a975-dda1f2380152.png">

**Comment by KaSroka** [comment]
Released v0.3.2 with new aiohttp version requirement (thanks to @operinko).

**Comment by h4de5** [comment]
new version release. please test.

would this also solve the issues with daikin_residential integration #87 ?

**Comment by haseat** [comment]
I just downloaded the new version, everything works again! Thanks!

**Comment by h4de5** [comment]
now working with HA 2023.3.1 as well.

thanks to everybody for their fast response!

**Comment by HeroBart** [comment]
> new version release. please test.
> 
> would this also solve the issues with daikin_residential integration #87 ?

The solaredge integration now works again, so I think the same fix would work for that integration as well! 👍
