### ISSUE TITLE
Error after upgrade to 2023.3.1

### ISSUE THREAD

**Issue by hufkens** [h4de5/home-assistant-toshiba_ac#115]
After upgrading Home Assistant to 2023.3.2, this Integration does not load anymore. For now I did a restore to the last 2022 version, but any help to fix it would be nice.

In the logs I see the following error message:

```
2023-03-05 10:52:53.967 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package toshiba-ac==0.3.1: ERROR: Cannot install toshiba-ac==0.3.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Hope that helps.

[edited]

I was on 2023.2.5 but the error was after upgrading to 2023.3.1. My bad

**Comment by h4de5** [comment]
the current toshiba-ac integration version requires at least HA 2023.0 due to said conflicting dependecies.

**Comment by hufkens** [comment]
@h4de5 I updated my issue, the version was wrong. It was after upgrading to 2023.3.1. My bad.

**Comment by hufkens** [comment]
Looks like after the 2023.3.1 I could indeed upgrade the Toshiba integration. So the issue is solved. Thanks for the quick reply.
