### ISSUE TITLE
Integration problem in last HA update

### ISSUE THREAD

**Issue by macmaniac1978** [h4de5/home-assistant-toshiba_ac#117]
with lasts HA update, the Toshiba AC integration doesn’t run and show an incompatible error 
<img width="1947" alt="Screenshot 2023-03-07 alle 19 52 10" src="https://user-images.githubusercontent.com/61051053/223525021-9c21babc-b95d-4341-86f3-50e6dccd647a.png">

**Comment by HeroBart** [comment]
You need to update the Toshiba AC plugin in HACS and restart. Then it'll work.

**Comment by macmaniac1978** [comment]
> You need to update the Toshiba AC plugin in HACS and restart. Then it'll work.

sorry, you are right.
I didn't know there was already the update.
Thank you

**Comment by HeroBart** [comment]
Not a problem at all, happy to help! :)
