### ISSUE TITLE
Feature: Implement indoor temperature as sensor

### ISSUE THREAD

**Issue by taher51** [h4de5/home-assistant-toshiba_ac#120]
Thank you for creating this integration. It has been an amazing addition to my smart home.

I want to ask is it possible to extract the indoor temperature and create a sensor of it. Just like the implementation of the outdoor temperature but for the indoor temperature.

**Comment by juliekoubova** [comment]
You can make a template sensor that will read the `current_temperature` of the climate entity. See https://www.home-assistant.io/integrations/template/

```yaml
- sensor:
    - name: Bedroom temperature
      state: {{ state_attr('climate.bedroom_mini_split', 'current_temperature') }}
      unit_of_measurement: "°C"

**Comment by h4de5** [comment]
I think that solution is suitable for all use cases.
