### ISSUE TITLE
Option to control Eco mode?

### ISSUE THREAD

**Issue by rudolphi** [h4de5/home-assistant-toshiba_ac#126]
In https://github.com/KaSroka/Toshiba-AC-control/blob/main/toshiba_ac/device/properties.py#L83 I see that KaSroka's API supports controlling Eco mode - which allows to optimize energy consumption especially to follow PV energy production. Would it be possible to add this parameter to the Home Assistant module? Probably quite similar to #10

**Comment by h4de5** [comment]
please test. eco mode is now added as a switch.

**Comment by rudolphi** [comment]
Yes, it works, many thanks. Thanks for the amazingly quick help:
![image](https://github.com/h4de5/home-assistant-toshiba_ac/assets/13907452/e50c8743-e9ef-41f9-afae-6bcbfd5d2250)
Now I can use free PV energy even better:-)
