### ISSUE TITLE
Trying to install Toshiba AC integration stuck in loop

### ISSUE THREAD

**Issue by pangelovski** [h4de5/home-assistant-toshiba_ac#127]
Hi, as the title says, I am trying to install the integration but its stuck saying "Please wait, starting configuration wizard for Toshiba AC". Has anyone seen this type of error before?

![Skärmbild 2023-05-28 225808](https://github.com/h4de5/home-assistant-toshiba_ac/assets/2341473/971bf402-bbf4-4744-9049-84b4d12b1697)

**Comment by h4de5** [comment]
please check the hime-assistant logs. maybe also the browser javascript console

**Comment by pangelovski** [comment]
A solu
