### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by chrisandsally** [h4de5/home-assistant-toshiba_ac#13]
Hi, Would love to use this within Home Assistant. I am new to it but working through it. I have HACS, Downloaded the Toshiba AC, Installed.

But Can't see any way to enter Username and Password although tried using File Editor and editing en.json.

  "config": {
    "abort": {
      "already_configured": "Device is already configured"
    },
    "error": {
      "cannot_connect": "Failed to connect",
      "invalid_auth": "Invalid authentication",
      "unknown": "Unexpected error"
    },
    "step": {
      "user": {
        "data": {
          "host": "Host",
          "password": "***",
          "username": "***"
        }
      }
    }
  },
  "title": "Toshiba AC"
}

Also, How to I see the Entities with Home Assistant?

Will happy pay for installation!

**Comment by h4de5** [comment]
hey. welcome to github.

the en.json is just for the translation - you should not modify them. 

if you have the toshiba_ac folder in your custom_components directory, you should just restart home-assistant and go to the integration settings, click on add and search for toshiba.

**Comment by chrisandsally** [comment]
Thank you, I have put them back. Restarted. Under Integrations I see the picture attached. 

"Update information" does not do anything, unsure what I need to do, put the username and password and load all the entities into Home Assistant.


![Screenshot 2021-08-28 at 19 18 16](https://user-images.githubusercontent.com/89684974/131227206-1641d52f-92cd-4bdc-925e-0510fd4f84ce.png)

**Comment by chrisandsally** [comment]
Got It, I did not know I needed to add it under HA as thought it was already in as under HACS.

Looks Like It has worked.  Thank you!

Chris

![Screenshot 2021-08-28 at 19 29 28](https://user-images.githubusercontent.com/89684974/131227486-17b688d4-eaa3-4072-acdb-d50fbad8fbc5.png)

**Comment by h4de5** [comment]
great!
