### ISSUE TITLE
Integration not setting up in version 2023.7.1

### ISSUE THREAD

**Issue by Stuke00** [h4de5/home-assistant-toshiba_ac#132]
Just sits at "Please wait, starting configuration wizard for toshiba_ac" and then gives an error.  Nothing shows up in HA Core log.  

![image](https://github.com/h4de5/home-assistant-toshiba_ac/assets/16128402/59ad7323-4172-431e-8a60-79ee7398b0b3)

**Comment by h4de5** [comment]
mmh. Just tried it after the update without problems? at which step did you the message?

**Comment by Stuke00** [comment]
It was as soon as I hit add integration from the HA integrations page. But seems to be working this morning.  Very weird. Sent from my iPhoneOn Jul 7, 2023, at 1:17 PM, Andi ***@***.***> wrote:﻿
mmh. Just tried it after the update without problems? at which step did you the message?
