### ISSUE TITLE
Authentication fails even though username and password are confirmed working in app

### ISSUE THREAD

**Issue by southpaw5271** [h4de5/home-assistant-toshiba_ac#133]
I am unable to set up the integration after install the latest version from HACS. I am told that the authentication failed even though I am 100% certain that the username and password entered into the app and the integration are the same.

**Comment by Michae11s** [comment]
Same issue here.

**Comment by h4de5** [comment]
I have no issues on my side. can you please try out the examples from the python api, they might show more detailed reasons.

**Comment by Michae11s** [comment]
As I investigate this might be a Market Segment issue?

I'm using the official Toshiba AC App however as I look at it this morning I notice its published by Midea, and is neither of the app listed in the readme.

[Toshiba AC NA](https://play.google.com/store/apps/details?id=com.midea.toshiba)

Also to go with that the [Midea AC LAN](https://github.com/georgezhao2010/midea_ac_lan) HACS integration finds my unit fine, so likely Toshiba is just rebranding Midea in my market segment. So this is not an issue just an unsupported device.

Might want to add that app to the readme as being unsupported and push those users to another integration.

**Comment by h4de5** [comment]
ah I see. this has been discussed multiple times already. see #83 #53.

@southpaw5271 can you confirm that you are on the right app? was it working before?

**Comment by southpaw5271** [comment]
@Michae11s @h4de5 I can confirm that I am using the Toshiba AC NA app published by GD Midea for iOS 16. This is a brand new unit to me so it is my first time installing the integration

**Comment by h4de5** [comment]
in this case I'll close this, because the this integration is unfortunately not compatible with Toshiba NA (north america) devices.
