### ISSUE TITLE
Devices unavailable 

### ISSUE THREAD

**Issue by olej24** [h4de5/home-assistant-toshiba_ac#139]
Hi

all of my AC units became unavailable yesterday. Still able to control via the Toshiba app. Is there a known server issue and others experiencing the same?

**Comment by chrisandsally** [comment]
Did you upgrade to 2023.8.0 by any chance, if so, then already reported #135 and being worked on.

**Comment by olej24** [comment]
Of HA Yes I did?
I wasn’t sure whether it was related to that or the recent Toshiba app update.

**Comment by h4de5** [comment]
close as duplicate #135
