### ISSUE TITLE
Question - Toshiba 4.0.00 to 4.2.00 Adapter Firmware Available

### ISSUE THREAD

**Issue by chrisandsally** [h4de5/home-assistant-toshiba_ac#141]
Hi Folks

Unsure how long this has been available as use HA for normal day to day control. Just loaded the Toshiba app and asked if I wanted to do a firmware update. From 4.0 to 4.2.  I remember we had an issue when we move to 3 to 4.  Has anyone tried it?

Thanks

**Comment by Sebazzz** [comment]
Which adapter? I have fw 2.2.0.0.

**Comment by chrisandsally** [comment]
The Wifi module is a WRE-T00AH10

**Comment by h4de5** [comment]
i am at adapter version 4.2.00 for quiet a while already.

wifi RB-N103S-G

**Comment by chrisandsally** [comment]
Thank you h4de5. I just went for it and upgraded firmware, all still works through HA. :) Thanks you all, hope this may help others users.
