### ISSUE TITLE
Invalid credentials 

### ISSUE THREAD

**Issue by tonyzielmanski** [h4de5/home-assistant-toshiba_ac#143]
Hello, I keep getting invalid credentials when trying to add as an integration, I have logged out of my Toshiba AC app and back in with the same credentials I enter when asked in Toshiba AC integration in home assistant and keep getting invalid

**Comment by h4de5** [comment]
please check if you have a supported device: #83

**Comment by Chaosspawn23** [comment]
I had a similar problem and was able to fix it by changing to a shorter and simpler password (old one was 24 letters with special characters, new one is 14 letters with just alphanumeric characters. I suspect that either the length or some special characters in the password caused the problems for me. Now, it works like a charm :)

**Comment by Jopinder** [comment]
Did the same, went from 24 alfanumerical characters in the password to 12 alfanumerical characters. Now I can log in to the integration.

**Comment by h4de5** [comment]
see #83
