### ISSUE TITLE
Toshiba AC Wi-Fi WPA3 support

### ISSUE THREAD

**Issue by zdeneksvarc** [h4de5/home-assistant-toshiba_ac#150]
It seems that Toshiba does not yet support Wi-Fi WPA3 on AC devices. Even for modern products like Haori.

Do you have other information or experience? I will contact the distributor, but maybe someone has already addressed this.

**Comment by KaSroka** [comment]
There are many IoT devices that does not support WPA3 and probably never will. That's why my IoT WiFi is on WPA2 and my "users" WiFi is on WPA3.

**Comment by h4de5** [comment]
nothing we can do here I guess.
