### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by beltracri** [h4de5/home-assistant-toshiba_ac#151]
I have a Toshiba VRF system connected with a LAN smart device control interface (BMS-IWF0320E).
I use toshiba AC control app on mobile.
I wanted to try if my systemis compatible but the integration gives me "Invalid authentication" message.
Credential works well on app, i tried also simplier user and password but noting.
Is this problem caused by incompatibility?

**Comment by gbrogna** [comment]
I am also having the same issue validating
Thank you

**Comment by beltracri** [comment]
I'm not that good and I don't know how to use PHP code... However I tried 5 different simpler credentials but none of them seem to work.
My doubts mainly concern the fact that my system could be compatible but the error lies precisely in the authentication.

**Comment by Zyxl72** [comment]
Go to Postman
https://www.postman.com/

There sign up for Free
then you can add a Request and enter as URL: 
https://mobileapi.toshibahomeaccontrols.com/api/Consumer/Login
then click on "Body" underneath the Url-Field, then next right select "JSON" and then
add this in the Field
{
    "username" : "<YOUR_USERNAME>",
    "password" : "<YOUR_PASSWORD>"
}

You see this in the Picture.
Then click "Send"
in the Response body you see if you were successful or not.

![login](https://github.com/h4de5/home-assistant-toshiba_ac/assets/87240400/1d3e47f5-a4b2-4a91-8c29-851dac9dfd40)

As mentioned in an other Issue, best add a new User to your Toshiba App simple by signing out, register a new user 
using the same eMail.

**Comment by repercussion** [comment]
Wanting to confirm that username is indeed the email address you used to sign up, correct? This is incongruous to that:

> add a new User to your Toshiba App simple by signing out, register a new user using the same eMail

**Comment by beltracri** [comment]
> Go to Postman https://www.postman.com/
> 
> There sign up for Free then you can add a Request, change from "GET" to "POST" and enter as URL: https://mobileapi.toshibahomeaccontrols.com/api/Consumer/Login then click on "Body" underneath the Url-Field, there select "raw" then next to the right select "JSON" and then add this in the Field { "username" : "<YOUR_USERNAME>", "password" : "<YOUR_PASSWORD>" }
> As mentioned in an other Issue, best add a new User to your Toshiba App simple by signing out, register a new user using the same eMail. Use 6-8 Letter for the username and as Password lower case characters and numbers only with a length of 6-8

Oh, thank you, I tried and the response is "Failed", so maybe I am using wrong credentials to try login!
I think I'm missing some steps of my setup because the BMS connection device was configured by installer and I suppose he used some "power user" credentials since i have no email registered.
I will try to ask him if there are some credential that I miss.

**Comment by Zyxl72** [comment]
#

> Wanting to confirm that username is indeed the email address you used to sign up, correct? This is incongruous to that:
> 
> > add a new User to your Toshiba App simple by signing out, register a new user using the same eMail

No the username is not your email.

When you first start the app you can either login or register (maybe you need to logout of the app first, when you already have done this) .
At register you can define your username and the password and then it asks for your email.
You can have serval usernames with different passwords with one email.
this email is the ID for your account where the ACs and the Estias are added.

**Comment by Zyxl72** [comment]
> > Go to Postman https://www.postman.com/
> > There sign up for Free then you can add a Request, change from "GET" to "POST" and enter as URL: https://mobileapi.toshibahomeaccontrols.com/api/Consumer/Login then click on "Body" underneath the Url-Field, there select "raw" then next to the right select "JSON" and then add this in the Field { "username" : "<YOUR_USERNAME>", "password" : "<YOUR_PASSWORD>" }
> > As mentioned in an other Issue, best add a new User to your Toshiba App simple by signing out, register a new user using the same eMail. Use 6-8 Letter for the username and as Password lower case characters and numbers only with a length of 6-8
> 
> Oh, thank you, I tried and the response is "Failed", so maybe I am using wrong credentials to try login! I think I'm missing some steps of my setup because the BMS connection device was configured by installer and I suppose he used some "power user" credentials since i have no email registered. I will try to ask him if there are some credential that I miss.

maybe you have to register a new user to your email..
with me it was like this. my first user i registered did not work, then i added a new user with the mentioned parameters and everything worked fine.

**Comment by Zyxl72** [comment]
if there are no further Questions this thread should be closed
