### ISSUE TITLE
Integration not loading/working after update to Home Assistant version 2023.12.3 from 2023.11.5

### ISSUE THREAD

**Issue by NickInManchester** [h4de5/home-assistant-toshiba_ac#160]
Had just used the integration via Lovelace interface in Home Assistant 11.5. Did update to latest 12.3. I did not try 12.0, 12.1 or 12.2.....but assume they would be the same.

Integration not loading so non of the entities or devices are available. For HA 12 (December 23) they had changed things in the climate code so presumably this has caused the fail. Hopefully an easy fix of dependencies.....

In my Logs:

Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 11:14:42 AM (3 occurrences)
Last logged: 11:15:48 AM

Unable to install package toshiba-ac==0.3.3: ERROR: Cannot install toshiba-ac==0.3.3 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Logger: homeassistant.setup
Source: setup.py:221
First occurred: 11:15:48 AM (1 occurrences)
Last logged: 11:15:48 AM

Setup failed for custom integration 'toshiba_ac': Requirements for toshiba_ac not found: ['toshiba-ac==0.3.3'].

My system currently:

Core   2023.12.3
Supervisor  2023.11.6
Operating System 11.2
Frontend  20231208.2

Error display attached:

![toshiba_integration_not_loading_HA12 3_15thDec2023](https://github.com/h4de5/home-assistant-toshiba_ac/assets/3940751/a5702a61-3d3e-44e5-8b46-f30b29a92e23)

**Comment by h4de5** [comment]
are you sure you are using the latest available version of this integration? in version 2023.12.0 the dependency has been updated to 0.3.4

**Comment by NickInManchester** [comment]
Sorry for the delay in responding.

Yep. It was me having forgotten to check HACS for updates. Even so, to get it all working and connected again I, in the end, seemed to have to strip the integration out completely, restart once or twice and then reinstall it into what then looked like a clean of Toshiba system.

All working again.

Thanks for your patience. Closed.

Nick
