### ISSUE TITLE
Toshiba AC turns on by itself without any set automations

### ISSUE THREAD

**Issue by SasoPavlic** [h4de5/home-assistant-toshiba_ac#161]
**Issue Description:**

I am experiencing an strange issue where my Toshiba AC unit automatically turns on without any configured automation or scene. This behavior is unexpected and occurs sporadically. Notably, this issue is only present with one of my two Toshiba AC units.

**Environment:**

- Home Assistant (HA) Version: 2023.12.2
- Toshiba AC Integration Version: v2023.12.0
- Affected Toshiba Product: RAS-B13J2KVSG-E
- Toshiba WIFI Module: RB-N106S-G (TYPE B)

**Additional Information:**

- The issue is not observed with my other Toshiba AC unit (TOSHIBA HAORI 4,6 kW), which is also connected to the same Home Assistant integration.
- There are no automations, scripts, or scenes within Home Assistant that could inadvertently trigger the AC unit.
- The unexpected activation of the AC does follow any patterns in terms of time or frequency. Usually early in the morning around 5:00 AM

**Relevant Logs and Screenshots:**
![toshibaac-error](https://github.com/h4de5/home-assistant-toshiba_ac/assets/24464688/0b021876-ab4f-4897-bbfb-6928a90f7696)

**Request:**
I am seeking assistance in diagnosing and resolving this issue. Any insights or suggestions from the community would be greatly appreciated.

**Comment by h4de5** [comment]
the only idea that comes to my mind is  that there is a schedule setup directly on your climate. 
to narrow it down, i would remove that one device from HA and see if its still happening.

**Comment by SasoPavlic** [comment]
@h4de5 I think you've pinpointed the issue perfectly. Thank you so much for your help – it's greatly appreciated. My family was starting to doubt my enthusiasm for HA, but this should change their minds! 

**Schedule setup in app, Toshiba Home AC Control:**
![image](https://github.com/h4de5/home-assistant-toshiba_ac/assets/24464688/366c6d03-3d80-493c-a479-d743c02f4947)
