### ISSUE TITLE
Indoor temperature as own sensor

### ISSUE THREAD

**Issue by karhukuoma** [h4de5/home-assistant-toshiba_ac#167]
How to add the current indoor temperature which is shown in climate entity as similar separate sensor as the `self._device.ac_outdoor_temperature`?

**Comment by h4de5** [comment]
see example config from the community forum: https://community.home-assistant.io/t/toshiba-home-ac-control/137698/166?u=h4de5

**Comment by karhukuoma** [comment]
Ok, thanks. For others looking for the answer. Go to developer tools -> template, paste `{{ states.climate.<yourtoshibadevice> }}` and it will show on the right side that the template value you are looking is "current_temperature".
The go to Settings - > Devices -> Helpers, create a new template helper -> choose sensor template
paste this to your sensor template
`{{ state_attr("climate.<yourtoshibadevice>",
"current_temperature")}}
`
and choose type temperature, celcius and measurement
