### ISSUE TITLE
TEMP_CELSIUS was used from toshiba_ac, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead

### ISSUE THREAD

**Issue by Snapperud** [h4de5/home-assistant-toshiba_ac#168]
From my HA log:
TEMP_CELSIUS was used from toshiba_ac, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead

Running on Home Assistant 2024.1.2

**Comment by boozeman** [comment]
And the same for this:

ENERGY_WATT_HOUR was used from toshiba_ac, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead, Running HA 2024.2.0

**Comment by boozeman** [comment]
ENERGY_WATT_HOUR was used from toshiba_ac, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead

The same for this. Issue #169 contains both of these.

**Comment by felixmueller** [comment]
Fixed in https://github.com/h4de5/home-assistant-toshiba_ac/releases/tag/2024.4.0.

Issue may be closed.
