### ISSUE TITLE
SILENT function of the outdoor unit

### ISSUE THREAD

**Issue by Didier3L** [h4de5/home-assistant-toshiba_ac#17]
For special functions, the SILENT function of the outdoor unit is missing.

![](https://community-assets.home-assistant.io/original/3X/3/a/3a420724f8d03257b6df990b2aee50bedb11295c.jpeg)

Didier

**Comment by h4de5** [comment]
see #10

**Comment by tetienne** [comment]
A select entity would be nice to handle this feature.

**Comment by h4de5** [comment]
are those related to the input selects?
https://www.home-assistant.io/integrations/input_select/

i think havnt seen them yet. how would you be able to set one of zhose merit functions in the frontend or the automations?

is this this?
https://developers.home-assistant.io/docs/core/entity/select

**Comment by tetienne** [comment]
Yes I'm talking about the [Select entity](https://developers.home-assistant.io/docs/core/entity/select).
Like today this component support climate and sensor, we can add select.

I didn't check how the merit worked yet. But if we can know the current value for the silent outdoor and also all the available values, it will be easy to implement.

**Comment by juliekoubova** [comment]
This has been implemented in #124
