### ISSUE TITLE
How much traffic we produce against the Toshiba API

### ISSUE THREAD

**Issue by boozeman** [h4de5/home-assistant-toshiba_ac#170]
Hi, 
This is not issue at all (At least for now) but How often this addon connects Toshiba API per minute? Seems like Mitsubishi has throtted the usage of api per user.

I suppose none of us want Toshiba to close the API due to too many requests.

Cheers

**Comment by h4de5** [comment]
i am not aware of any regular requests done by the Integration. the state is managed by the underlying python package:

https://github.com/KaSroka/Toshiba-AC-control

**Comment by KaSroka** [comment]
Author of Toshiba AC control here. We are doing one API call to gather energy consumption of all devices every 10 min. We are also doing one API call to get current device state for each device every 30 min (this is done to make sure our local state is correct as AMQP is only sending us diff to the previous state, so there is a possibility that we have missed a notification and our local state is incorrect). So in total we are doing 6 + 2 * num_of_devices HTTP API calls per hour.
