### ISSUE TITLE
Why is the Fan Mode not available for automation? 

### ISSUE THREAD

**Issue by AnssiLaiho** [h4de5/home-assistant-toshiba_ac#172]
Hi! I was trying to make an automation for my Toshiba Haori AC in Home assistant, but the Fan control is not present in the controls of the device (even though it is available in the GUI of the device in HAS overview). At least not in the GUI mode? How would it be possible to control it ?

**Comment by h4de5** [comment]
try service: climate.set_fan_mode to: low

**Comment by AnssiLaiho** [comment]
Yes, that works! Thankyou!

**Comment by h4de5** [comment]
you are welcome.
