### ISSUE TITLE
Support for Toshiba AC NA app?

### ISSUE THREAD

**Issue by ICE0124** [h4de5/home-assistant-toshiba_ac#174]
Is this ever planned to also integrate with this Toshiba AC app too?

**Comment by h4de5** [comment]
Toshiba North America have a different app and possible protocol and server infrastructure. at least I do not plan to implement a support for this.

have a look at #53

**Comment by ICE0124** [comment]
> Toshiba North America have a different app and possible protocol and server infrastructure. at least I do not plan to implement a support for this.
> 
> have a look at #53

Okay thanks you for your explanation.
