### ISSUE TITLE
Support for reading and updating timer programs

### ISSUE THREAD

**Issue by felixmueller** [h4de5/home-assistant-toshiba_ac#176]
Hello,
I am very happy that this Home Assistant plugin exists, thank you very much for providing it!
I was wondering if it is possible to read and update the **timer programs** with Home Assistant. This is the only function for which I still need the Toshiba app.
Is this possible via the API? That would be really great!
Best,
Felix

![IMG_73E20775D9CA-1](https://github.com/h4de5/home-assistant-toshiba_ac/assets/115331/b765a95f-7962-4be3-bb0d-e6891e04c8f8)

**Comment by felixmueller** [comment]
Hi Andi @h4de5,

of course I could use HA Automations to control the AC's off time. But my intent is to support the native device feature that is also displayed as LED on the device itself. 

It should be as simple as displaying the current off time (e.g. 19:21) in HA as text value and for controlling it, a switch or select element should be enough to set timers for 0.5h, 1h, 1,5h and so on (like the Toshiba App).

I hope that a feature like this is possible and you are willing to implement it. It is the only thing I really miss in HA compared to the Toshiba App. 

Thank you very much!

**Comment by h4de5** [comment]
i see. you might nees to check if this is supported by the underlying python lib that does the communications.
please reopen if this is confirmed.
