### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by SkillfulHacking** [h4de5/home-assistant-toshiba_ac#182]
I have entered my credentials correctly for the Toshiba AC NA app several times to no avail
Attempted password reset.  was still able to login to app using email and password. 
Still unable to login via home assistant integration.   Hoping this is a temporary issue with Toshiba but will report back if status changes.

**Comment by h4de5** [comment]
Toshiba North America have a different app and possible protocol and server infrastructure. at least I do not plan to implement a support for this.

have a look at https://github.com/h4de5/home-assistant-toshiba_ac/issues/53
