### ISSUE TITLE
Implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature

### ISSUE THREAD

**Issue by albaintor** [h4de5/home-assistant-toshiba_ac#187]
Hi,

in my homeassistant logs I have this warning message :

`Entity climate.chambre_edouard_climatisation (<class 'custom_components.toshiba_ac.climate.ToshibaClimate'>) implements HVACMode(s): off, auto, cool, heat, dry, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/h4de5/home-assistant-toshiba_ac/issues`

Thank you for your support

**Comment by h4de5** [comment]
should be fixed now. see latest release https://github.com/h4de5/home-assistant-toshiba_ac/releases/tag/2024.6.1
