### ISSUE TITLE
Climate entity no longer being provided

### ISSUE THREAD

**Issue by narfotic** [h4de5/home-assistant-toshiba_ac#192]
I am getting following error for all the climate entities from toshiba ac: "This entity is no longer being provided by the toshiba_ac integration. If the entity is no longer in use, delete it in settings."

Toshiba ac integration v2024.6.1

HA:
Core 2024.7.3
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

Toshiba adapter firmware version 4.4.00

**Comment by beandi** [comment]
Had the same problem yesterday, deactivating and activating the integration solved the issue for me (no need for signing in again)

**Comment by narfotic** [comment]
Weird! That helped. Rebooting before did not.
