### ISSUE TITLE
Device not found after a day.

### ISSUE THREAD

**Issue by TT1312555** [h4de5/home-assistant-toshiba_ac#193]
This happens everyday, please advise.

2024-07-26 09:31:13.089 ERROR (MainThread) [custom_components.toshiba_ac.climate] Error during connection to Toshiba server 0, message='Attempt to decode JSON with unexpected mimetype: text/html'
2024-07-26 09:31:13.102 ERROR (MainThread) [homeassistant.helpers.entity_platform] toshiba_ac raises exception ConfigEntryNotReady in forwarded platform climate; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups

**Comment by h4de5** [comment]
this does happen quiet often. when the toshiba server is not reachable this exeption is thrown. best you can do is wait until its reachable again, querying too often does also not help. :(

**Comment by TT1312555** [comment]
I see.

If I reset HA or reload it, it will work. So I am not sure which is the
exact reason.

**Comment by h4de5** [comment]
usually reloading the extension (from the toshiba integration page) should do the trick.

**Comment by TT1312555** [comment]
Is there an automation to reload it? For example, reloading it everyday at
12PM.

Best regards,
Nart

**Comment by chrisandsally** [comment]
Also having the same issue, our the last few months. A simple reload kicks it back in, so is there a way to trap this and fore a reload, or to automate a schedule reload?

**Comment by k3067e3** [comment]
![Screenshot_2024-07-27-10-57-10-473_io homeassistant companion android](https://github.com/user-attachments/assets/a1a7e194-60d2-437b-a983-22696ffd185d)

**Comment by TT1312555** [comment]
> ![Screenshot_2024-07-27-10-57-10-473_io homeassistant companion android](https://private-user-images.githubusercontent.com/31401888/352711704-a1a7e194-60d2-437b-a983-22696ffd185d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwODcyMTEsIm5iZiI6MTcyMjA4NjkxMSwicGF0aCI6Ii8zMTQwMTg4OC8zNTI3MTE3MDQtYTFhN2UxOTQtNjBkMi00MzdiLWE5ODMtMjI2OTZmZmQxODVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDEzMjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZTY3NmM3Zjg2NzAwNjM0Y2MzMDkyZmYwOTFjMzg4ZTBiN2RkOWQ1YmVhNDdhYzg3ZmJkN2MyZWVkZjZhNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rlcMnetz7-D8z3NS-WoP96DfNEbYwEZoEKrsm9u50xs)

Thank you. Could you please expand them as well? I am new so I am not sure what to configure.

![image](https://github.com/user-attachments/assets/5bcb84cd-f940-44d9-8606-90387d0407bf)

**Comment by k3067e3** [comment]
![Screenshot_2024-07-27-19-49-06-896_io homeassistant companion android](https://github.com/user-attachments/assets/16105286-cb39-42ff-a24f-5fd68ad12689)

**Comment by k3067e3** [comment]
EG is my entity for Toshiba AC as named in Toshiba app

**Comment by TT1312555** [comment]
> EG is my entity for Toshiba AC as named in Toshiba app

Am I doing this right? So far no trigger.
I have 2 ACs, one on the 1st and the other on the 2nd floor.

![image](https://github.com/user-attachments/assets/5f3b9044-8f16-45e8-b170-c5c1a5b6b88c)

**Comment by k3067e3** [comment]
I am also no specialist, but have a look here. https://github.com/h4de5/home-assistant-toshiba_ac/issues/193#issuecomment-2254082102

My And if Section is empty. I have everything handled in the Then Do section, as you can see in the screenshot.
I have also a multiple split Air Condition, entity EG & 1OG, but I only trigger one of them, because when one is offline, the other is offline too.
