### ISSUE TITLE
Credentials invalid

### ISSUE THREAD

**Issue by Fudal** [h4de5/home-assistant-toshiba_ac#197]
For a long time now I have had a problem where I cannot perform any action on the air conditioning because I have the message: Credentials invalid, could not connect.

When this message appears, I restart Home Assistant and everything works fine until the next time (e.g. the next day) when the same problem occurs again.
![Screenshot_20240808_165523_Home Assistant](https://github.com/user-attachments/assets/a289db30-2e0b-4d1f-870a-1f6b64cc502e)

**Comment by h4de5** [comment]
please try to use the search function

**Comment by jasiek-b** [comment]
Hi, have the same problem and I can't really find the answer.
Integration connects and after some time stops working, but not fully, because it still reads the status, just can't send any commend. When I try e.g. to start or stop AC, there is an error "Credentials invalid, could not connect.", but when I start AC manually or from application, HA sees the change of state of the unit almost immediately.
I found similar issues #195 and #199, but the point is, I installed HA just 3 days ago and added Toshiba integration just yesterday.

**Comment by jasiek-b** [comment]
I was almost sure, I will write that issue no longer appears after I upgraded HA to 2024.8.3 6 days ago, but unfortunately it showed up again just few minutes ago :(
Still there is additional information - maybe helpful. Whole family was out of home for few last days and I was only checking remotely (maybe once a day) if I can start and stop AC. So after upgrade everything worked for about 24h, then we were out and returned today - soon the issue appeared again.

**Comment by joepvanboekel** [comment]
I have the same error, this happend when we upgraded from probably 2024.7.3 to 2024.8.0, we are using version 2024.8.0 of the Toshiba integration

After rebooting(not reload) the whole home Assistant it works for a maximum of 1 day or a few commands and then it starts whining about credentials invalid again

I have another building running home Assistant at version 2024.7.3 together with the 2024.6.1 version of the Toshiba, this install works good (with sometimes slow refresh of status when the Ac’s where switched on by remote control)

So can we somehow help debug this problem ?

**Comment by h4de5** [comment]
in version 2024.8 a randomness to the regular status check was added, because toshiba registered the many users querying the API all at each full hour as a DoS request and throttled access to it. 

going back to the old version might work - up until to the point when too many users do the same and the throttling by toshiba is activated again.

@KaSroka about the invalid credential message: do you think that could be another toshiba driven limitation or is it possible that an access token is now used for too long without a refresh?

at this point I cannot verify the issue at all, because since the last version update i had no problems with my climate at all.

**Comment by joepvanboekel** [comment]
Perhaps good to know: The data of the airco’s is still refreshed in HA after getting the credentials error

So HA still knows the current (with the designed randomness) status of the airco’s but is unable to control

**Comment by KaSroka** [comment]
As I'm not seeing the issue, same as @h4de5 it's harder to debug. Can someone check if removing and adding back the integration changes anything?

**Comment by joepvanboekel** [comment]
@KaSroka as I need the other building to be working with the AC integration, I can't upgrade that one to 2024.8.0 to test that out

in my private HA, I have removed the Toshiba AC integration from Devices & Services, i've rebooted HA, and added back the integration

at this moment sending commands works again (but it always worked after rebooting HA for a while recentely)
I will check later today if it still works

**Comment by jasiek-b** [comment]
Can someone check if removing and adding back the integration changes anything?

It helps temporarily, same way as reboot of HA. It's not a permanent solution.

**Comment by KaSroka** [comment]
Next step, please run this in your HA instance:
`/config cat /config/.storage/core.config_entries | jq '.data.entries[] | select(.domain == "toshiba_ac") | .data.sas_token  | split("&") | map(select(startswith("se="))) | .[0] | ltrimstr("se=") | tonumber | todate'` this will print the expiry date of the sas token received from the cloud. In my scenario issued tokens are valid for 100 years.

Also after reboot do you see this in logs?
`Initial connection failed, trying to get new sas_token...`

**Comment by jasiek-b** [comment]
Indeed - 100 years:
➜  ~ cat /config/.storage/core.config_entries | jq '.data.entries[] | select(.domain == "toshiba_ac") | .data.sas_token  | split("&") | map(select(startswith("se="))) | .[0] | ltrimstr("se=") | tonumber | todate'         
"2124-08-13T12:07:11Z"

**Comment by jasiek-b** [comment]
> Also after reboot do you see this in logs? `Initial connection failed, trying to get new sas_token...`
Can't find anything like that immediately after restart. Or you want me to wait for the issue and then restart and check?

**Comment by KaSroka** [comment]
If you wait for the issue and then restart it will be the best

**Comment by KaSroka** [comment]
Also, can you please enable debug logs and post the log output when issue happens?

To enable logs, please add this to your configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    # log level toshiba-ac
    toshiba_ac: debug
    custom_components.toshiba_ac: debug
```

**Comment by Fudal** [comment]
Maybe it help - my lady log after rerun HA:
```
Rejestrator: homeassistant.helpers.entity_platform
Źródło: helpers/entity_platform.py:415
Pierwsze zdarzenie: 12:31:18 (1 zdarzenia)
Ostatnio zalogowany: 12:31:18

toshiba_ac raises exception ConfigEntryNotReady in forwarded platform climate; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
```

**Comment by jasiek-b** [comment]
This is what I see in the log when issue "is active" - before restart. I added logger: to configuration.yaml after first occurrence of the the problem today, then I tried to change setting for AC twice.

Rejestrator: homeassistant.components.websocket_api.http.connection
Źródło: components/websocket_api/commands.py:245
integracja: Home Assistant WebSocket API (dokumentacja, Problemy)
Pierwsze zdarzenie: 13:56:03 (3 zdarzenia)
Ostatnio zalogowany: 14:09:26

[547330632016] Unexpected exception
[547374391520] Unexpected exception
[547006254672] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 36, in handle_result
    return await callback.completion()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/common/async_adapter.py", line 91, in completion
    return await self.future
           ^^^^^^^^^^^^^^^^^
azure.iot.device.common.transport_exceptions.UnauthorizedError: Connection Refused: not authorised.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 764, in async_handle_set_swing_mode_service
    await self.async_set_swing_mode(swing_mode)
  File "/config/custom_components/toshiba_ac/climate.py", line 223, in async_set_swing_mode
    await self._device.set_ac_swing_mode(feature_list_id)
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 318, in set_ac_swing_mode
    await self.send_state_to_ac(state)
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 259, in send_state_to_ac
    await self.amqp_api.send_message(str(fcu_to_ac))
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/amqp_api.py", line 100, in send_message
    await self.device.send_message(msg)
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/aio/patch_documentation.py", line 60, in send_message
    return await super(IoTHubDeviceClient, self).send_message(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 359, in send_message
    await handle_result(callback)
  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 44, in handle_result
    raise exceptions.CredentialError("Credentials invalid, could not connect") from e
azure.iot.device.exceptions.CredentialError: Credentials invalid, could not connect

**Comment by jasiek-b** [comment]
I just restarted HA and there is following entry:
Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.toshiba_ac
Źródło: custom_components/toshiba_ac/__init__.py:40
integracja: Toshiba AC (dokumentacja, Problemy)
Pierwsze zdarzenie: 14:13:25 (1 zdarzenia)
Ostatnio zalogowany: 14:13:25

Initial connection failed, trying to get new sas_token...

**Comment by KaSroka** [comment]
I have created #203 that *may* fix the issue.

**Comment by h4de5** [comment]
closing for now. please comment if this is still an issue.

**Comment by Fudal** [comment]
I have again the same problem after upgrade to 2024.10 (and 2024.10.1).

**Comment by KaSroka** [comment]
Please attach debug logs. Induction is in my comment above: https://github.com/h4de5/home-assistant-toshiba_ac/issues/197#issuecomment-2336617234

**Comment by FRight80** [comment]
Seem to be having the same issue for the last weeks.
On Toshiba version 2024.9.0
Currently running HA: 2024.10.1

24 hours after restart the credentials becomes invalid. See log below:

> 2024-10-10 18:34:58.531 ERROR (MainThread) [toshiba_ac.device] State reload failed: 
> 2024-10-10 19:27:11.400 INFO (MainThread) [custom_components.toshiba_ac.climate] Toshiba Climate setting hvac_mode: off
> 2024-10-10 20:16:05.847 WARNING (callback) [azure.iot.device.common.handle_exceptions] Exception caught in background thread.  Unable to handle.
> 2024-10-10 20:16:05.848 WARNING (callback) [azure.iot.device.common.handle_exceptions] ['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: Unexpected disconnection\n']
> 2024-10-10 20:16:06.030 WARNING (callback) [azure.iot.device.common.handle_exceptions] Exception caught in background thread.  Unable to handle.
> 2024-10-10 20:16:06.031 WARNING (callback) [azure.iot.device.common.handle_exceptions] ['azure.iot.device.common.transport_exceptions.UnauthorizedError: Connection Refused: not authorised.\n']
> 2024-10-10 20:16:06.038 WARNING (pipeline) [azure.iot.device.common.pipeline.pipeline_stages_base] ConnectionStateStage: DisconnectEvent received while in unexpected state - ConnectionState.DISCONNECTED
> 2024-10-10 20:16:06.042 WARNING (callback) [azure.iot.device.common.handle_exceptions] Exception caught in background thread.  Unable to handle.
> 2024-10-10 20:16:06.042 WARNING (callback) [azure.iot.device.common.handle_exceptions] ['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: Unexpected disconnection\n']
> 2024-10-10 20:34:34.054 INFO (MainThread) [custom_components.toshiba_ac.climate] Toshiba Climate setting hvac_mode: off
> 2024-10-10 20:34:34.249 WARNING (pipeline) [azure.iot.device.common.pipeline.pipeline_stages_base] ConnectionStateStage: DisconnectEvent received while in unexpected state - ConnectionState.DISCONNECTED
> 2024-10-10 20:34:34.252 WARNING (callback) [azure.iot.device.common.handle_exceptions] Exception caught in background thread.  Unable to handle.
> 2024-10-10 20:34:34.253 WARNING (callback) [azure.iot.device.common.handle_exceptions] ['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: Unexpected disconnection\n']
> 2024-10-10 20:34:34.243 ERROR (MainThread) [homeassistant.components.automation.ac_living_room] AC Living Room: Choose at step 1: Switch off above 24: Error executing script. Unexpected error for device at pos 1: Credentials invalid, could not connect
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 36, in handle_result
>     return await callback.completion()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/azure/iot/device/common/async_adapter.py", line 91, in completion
>     return await self.future
>            ^^^^^^^^^^^^^^^^^
> azure.iot.device.common.transport_exceptions.UnauthorizedError: Connection Refused: not authorised.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 780, in _async_device_step
>     await device_action.async_call_action_from_config(
>   File "/usr/src/homeassistant/homeassistant/components/device_automation/action.py", line 72, in async_call_action_from_config
>     await platform.async_call_action_from_config(hass, config, variables, context)
>   File "/usr/src/homeassistant/homeassistant/components/climate/device_action.py", line 98, in async_call_action_from_config
>     await hass.services.async_call(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
>     single_response = await _handle_entity_call(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
>     result = await task
>              ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 772, in async_handle_set_hvac_mode_service
>     await self.async_set_hvac_mode(hvac_mode)
>   File "/config/custom_components/toshiba_ac/climate.py", line 194, in async_set_hvac_mode
>     await self._device.set_ac_status(ToshibaAcStatus.OFF)
>   File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 246, in set_ac_status
>     await self.send_state_to_ac(state)
>   File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 236, in send_state_to_ac
>     await self.amqp_api.send_message(str(fcu_to_ac))
>   File "/usr/local/lib/python3.12/site-packages/toshiba_ac/utils/amqp_api.py", line 107, in send_message
>     await self.device.send_message(msg)
>   File "/usr/local/lib/python3.12/site-packages/azure/iot/device/aio/patch_documentation.py", line 60, in send_message
>     return await super(IoTHubDeviceClient, self).send_message(message)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 359, in send_message
>     await handle_result(callback)
>   File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 44, in handle_result
>     raise exceptions.CredentialError("Credentials invalid, could not connect") from e
> azure.iot.device.exceptions.CredentialError: Credentials invalid, could not connect
>

**Comment by michalkotas** [comment]
Today, I encountered what was likely the same error. I was able to turn the AC on (so the login/password was correct), but after a few seconds, I received an error.

` File "/usr/local/lib/python3.12/site-packages/azure/iot/device/common/async_adapter.py", line 91, in completion
    return await self.future
           ^^^^^^^^^^^^^^^^^
azure.iot.device.common.transport_exceptions.UnauthorizedError: Connection Refused: not authorised.`

`  File "/usr/local/lib/python3.12/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 44, in handle_result
    raise exceptions.CredentialError("Credentials invalid, could not connect") from e
azure.iot.device.exceptions.CredentialError: Credentials invalid, could not connect`

**Comment by Fudal** [comment]
@h4de5 @KaSroka the issue is still exist, should be open
