### ISSUE TITLE
New install - cannot authenticate

### ISSUE THREAD

**Issue by jpravetz** [h4de5/home-assistant-toshiba_ac#198]
I have one device that I have configured via the Toshiba AC app. I am trying to add the Toshiba AC integration but authentication fails. I used my gmail address when I registered with the app. I try using the email address as the username with the integration and it fails (Invalid authentication). Same if I try using my email address minus the `@gmail.com`. Same if I use the 8-digit ID that the Toshiba app appears to assign me.

Is something broken? Ideas?

Here are some log entries:

```
Logger: custom_components.toshiba_ac.config_flow
Source: custom_components/toshiba_ac/config_flow.py:52
integration: Toshiba AC ([documentation](https://github.com/h4de5/home-assistant-toshiba_ac), [issues](https://github.com/h4de5/home-assistant-toshiba_ac/issues))
First occurred: 5:57:53 PM (4 occurrences)
Last logged: 6:10:05 PM
Toshiba connection OK
```

```
Logger: custom_components.toshiba_ac.config_flow
Source: custom_components/toshiba_ac/config_flow.py:46
integration: Toshiba AC ([documentation](https://github.com/h4de5/home-assistant-toshiba_ac), [issues](https://github.com/h4de5/home-assistant-toshiba_ac/issues))
First occurred: 5:57:53 PM (4 occurrences)
Last logged: 6:10:05 PM
Toshiba connection error Invalid UserName or Password
```

Thanks, Jim

**Comment by h4de5** [comment]
please use search function
