### ISSUE TITLE
Home integration assistant

### ISSUE THREAD

**Issue by Didier3L** [h4de5/home-assistant-toshiba_ac#2]
Hello 
I also have a Toshiba air conditioning including Seiya RAS-B07J2KVG-E splits
All splits are equipped with a WIFI Module - RB-102S-G

I put all the files in `/config/python_scripts`

I would like to test a script but I don't understand how to integrate it into Home Assistant

can you help me ?

**Comment by h4de5** [comment]
I am sorry - I am far from finishing the integration, I only started this to play around with the scheduler webservice.
I'll create a release once I have a working integration.
