### ISSUE TITLE
"Unknown error occurred" when logging in

### ISSUE THREAD

**Issue by taraldb** [h4de5/home-assistant-toshiba_ac#204]
Hi,

I get this error when i try to log in.
![image](https://github.com/user-attachments/assets/e6cf3202-81a3-4b41-874b-3f9eb9d96177)
(username and password changed to other values for the screenshot)

From home-assistant.log
```log
2024-09-11 07:35:57.238 ERROR (MainThread) [custom_components.toshiba_ac.config_flow] Toshiba connection OK
```

Could not find any other issues mentioning this. Any idea what I might be doing wrong?

**Comment by h4de5** [comment]
https://github.com/h4de5/home-assistant-toshiba_ac/issues/202
https://github.com/h4de5/home-assistant-toshiba_ac/issues/181
https://github.com/h4de5/home-assistant-toshiba_ac/issues/151
https://github.com/h4de5/home-assistant-toshiba_ac/issues/142
https://github.com/h4de5/home-assistant-toshiba_ac/issues/86

**Comment by taraldb** [comment]
Concating password to 20 chars fixed it. Seems they don't support passwords longer than 20 chars...
