### ISSUE TITLE
Showing Unavailable in Home Assistant

### ISSUE THREAD

**Issue by chrisandsally** [h4de5/home-assistant-toshiba_ac#21]
Showing unavailable within HA.  Below only thing I can see in the log file.

Logger: homeassistant.config_entries
Source: custom_components/toshiba_ac/__init__.py:30 
Integration: Toshiba AC (documentation, issues) 
First occurred: 8:14:23 (2 occurrences) 
Last logged: 8:22:05

Error setting up entry studio109 for toshiba_ac
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/toshiba_ac/__init__.py", line 30, in async_setup_entry
    entry.data["device_id"],
KeyError: 'device_id'

**Comment by h4de5** [comment]
please try to remove toshiba ac from the integration list, and add it again. (the part where you add your username and password). this should setup this correctly.

**Comment by chrisandsally** [comment]
Yes, that did it, Thank you.
