### ISSUE TITLE
HA full with updated Core 2024.11.3 on NUC - Log with WARNINGS and then ERRORS

### ISSUE THREAD

**Issue by WladyTee** [h4de5/home-assistant-toshiba_ac#212]
Hi everybody, 
just to share with you and qualify possible fixes.

Since 2024.11 a lot of delays appear in the log, where it looks to generate also other cascaded issues (I'm trying to understand the possible connections between several secondary failures and reloads).

Please advise if you see any remarkable note or hint.
I believe that systemmonitor is somehow involved.
Here the log items:

=====================================================
=====================================================
=====================================================

ERROR
Registratore: toshiba_ac.device
Fonte: runner.py:189
Prima occorrenza: 23 novembre 2024 alle ore 15:34:47 (107 occorrenze)
Ultima registrazione: 23:01:58

State reload failed:

=====================================================

ERROR
Registratore: homeassistant.components.switch
Fonte: helpers/entity_platform.py:409
Integrazione: Interruttore ([documentazione](https://www.home-assistant.io/integrations/switch), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
Prima occorrenza: 23 novembre 2024 alle ore 15:04:35 (1 occorrenze)
Ultima registrazione: 23 novembre 2024 alle ore 15:04:35

Setup of platform toshiba_ac is taking longer than 60 seconds. Startup will proceed without waiting any longer.

=====================================================

ERROR
Registratore: homeassistant.components.sensor
Fonte: helpers/entity_platform.py:409
Integrazione: Sensore ([documentazione](https://www.home-assistant.io/integrations/sensor), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
Prima occorrenza: 23 novembre 2024 alle ore 15:04:35 (1 occorrenze)
Ultima registrazione: 23 novembre 2024 alle ore 15:04:35

Setup of platform toshiba_ac is taking longer than 60 seconds. Startup will proceed without waiting any longer.

=====================================================

ERROR
Registratore: homeassistant.components.select
Fonte: helpers/entity_platform.py:409
Integrazione: Seleziona ([documentazione](https://www.home-assistant.io/integrations/select), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+select%22))
Prima occorrenza: 23 novembre 2024 alle ore 15:04:35 (1 occorrenze)
Ultima registrazione: 23 novembre 2024 alle ore 15:04:35

Setup of platform toshiba_ac is taking longer than 60 seconds. Startup will proceed without waiting any longer.

=====================================================

ERROR
Registratore: homeassistant.components.climate
Fonte: helpers/entity_platform.py:409
Integrazione: Climatizzatore ([documentazione](https://www.home-assistant.io/integrations/climate), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
Prima occorrenza: 23 novembre 2024 alle ore 15:04:35 (1 occorrenze)
Ultima registrazione: 23 novembre 2024 alle ore 15:04:35

Setup of platform toshiba_ac is taking longer than 60 seconds. Startup will proceed without waiting any longer.

=====================================================

WARNING
Registratore: homeassistant.components.sensor
Fonte: runner.py:189
Integrazione: Sensore ([documentazione](https://www.home-assistant.io/integrations/sensor), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
Prima occorrenza: 23 novembre 2024 alle ore 15:04:20 (2 occorrenze)
Ultima registrazione: 23 novembre 2024 alle ore 15:04:35

Setup of sensor platform toshiba_ac is taking over 10 seconds.
Setup of sensor platform systemmonitor is taking over 10 seconds.

=====================================================

WARNING
Registratore: homeassistant.components.switch
Fonte: runner.py:189
Integrazione: Interruttore ([documentazione](https://www.home-assistant.io/integrations/switch), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
Prima occorrenza: 23 novembre 2024 alle ore 15:04:20 (1 occorrenze)
Ultima registrazione: 23 novembre 2024 alle ore 15:04:20

Setup of switch platform toshiba_ac is taking over 10 seconds.

=====================================================

WARNING
Registratore: homeassistant.components.select
Fonte: runner.py:189
Integrazione: Seleziona ([documentazione](https://www.home-assistant.io/integrations/select), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+select%22))
Prima occorrenza: 23 novembre 2024 alle ore 15:04:20 (1 occorrenze)
Ultima registrazione: 23 novembre 2024 alle ore 15:04:20

Setup of select platform toshiba_ac is taking over 10 seconds.

=====================================================

WARNING
Registratore: homeassistant.components.climate
Fonte: runner.py:189
Integrazione: Climatizzatore ([documentazione](https://www.home-assistant.io/integrations/climate), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
Prima occorrenza: 23 novembre 2024 alle ore 15:04:20 (1 occorrenze)
Ultima registrazione: 23 novembre 2024 alle ore 15:04:20

Setup of climate platform toshiba_ac is taking over 10 seconds.

=====================================================
=====================================================
=====================================================

Thanks a lot for your time and happy TOSHIBA_AC use!
BR, Wlady

**Comment by albaintor** [comment]
Hi, probably the same issue as reported in https://github.com/h4de5/home-assistant-toshiba_ac/issues/207

**Comment by h4de5** [comment]
please check latest release.
If the error persists, please make sure it is not related to a possible restricted access to the Toshiba API before reopening the issue.
