### ISSUE TITLE
Energy consumption not showing up in 2021.8.8

### ISSUE THREAD

**Issue by haseat** [h4de5/home-assistant-toshiba_ac#24]
I updated Toshiba AC to the latest version 2021.8.8 via HACS today and restarted my HA instance. Toshiba AC then was was not working (my AC was unavailable, if that happens I have to uninstall/install Toshiba AC, which I did). After this, the Toshiba AC integration still showed 1 device and 1 entity:

![image](https://user-images.githubusercontent.com/61622258/132130088-ada9734e-a8b5-4761-9aa5-3086ac6955c0.png)

Did I forget anything?

Thanks!
Robert

**Comment by Cecchellone** [comment]
Mine is now capable of reading the external temperature ❤
But also for me the energy sensor is not popping out...
![immagine](https://user-images.githubusercontent.com/12474025/132132073-70a12b8d-dc40-42b4-bd4a-2992136549ca.png)
(just ignore the writes out of bounds, it's just that i'm using Italian language)

Anyway thanks for your work! It's getting more awesome day by day!

**Comment by haseat** [comment]
Right, after another reboot the outdoor temperature showed up as well :-), but still no energy consumption.

**Comment by h4de5** [comment]
did the energy consumption work before?
it tries to detect whenever the device is capable of monitoring it and if not, it should write an INFO message in the logs. in case the message is there, while the device is showing energy consumption in the toshiba app, i have to find a new way for checking that support.

**Comment by Cecchellone** [comment]
Fornow it has never worked, i was just hoping with the latest updates it would start working...
(instead i got a supervisor random death and i had to reinstall all the thing)
By the way in the app it shows the energy tab (with values) and in the logs if i search for "toshiba" it just return me one warning line:
`WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration toshiba_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

My model is an Haori `ras-b13n4kvrg-e` and except for the energy-thing, it's fully working if you want to add it in the readme.

**Comment by h4de5** [comment]
the warning about custom components cones from HA, for every component.

in order to show Info-level messages, you may have to modify your logger settings in your configuration:

```
logger:
  default: warning
  logs:
    custom_components.toshiba_ac: info
    toshiba_ac: info
```

instead of **info** you could also set it to **debug** for even more messages.
but if it does show up in the app, it should be there in the integration as well.

**Comment by haseat** [comment]
https://pastebin.com/wWJZhRbp

I replaced my username with "username" (twice in the paste) and my password with "password" (once in the paste) for obvious reasons :-).

**Comment by h4de5** [comment]
I removed the link as it still contains bearier and access_tokens.
it does say: "AC device does not seem to support energy monitoring" so it seems detecting whenever power monitoring is supported or not, does not yet work..

thanks for testing this.

**Comment by Cecchellone** [comment]
ok, i added the logger entry in debug mode in my configs and it now show this:
https://pastebin.com/C6cM2X0x
(i carefully deleted any sensitive information i think)

anyway the app is capable of showing me this:
![photo_2021-09-06_12-15-22](https://user-images.githubusercontent.com/12474025/132203930-f03aaeaf-6603-4f98-ad6a-43fb7894ca2e.jpg)

tell me if i can be of any further help!

**Comment by KaSroka** [comment]
@h4de5 the problem seems to be with the check you have added:
```
2021-09-06 11:34:05 INFO (MainThread) [custom_components.toshiba_ac.sensor] AC device does not seem to support energy monitoring
2021-09-06 11:34:05 DEBUG (MainThread) [toshiba_ac.http_api] Response code: 200, JSON: {'ResObj': [{'ACName': None, 'ACDeviceUniqueId': '4b859d0a-23b2-456b-95fc-d401620f24d7', 'EnergyConsumption': [{'Time': '01', 'Energy': 0}, {'Time': '02', 'Energy': 0}, {'Time': '03', 'Energy': 0}, {'Time': '04', 'Energy': 0}, {'Time': '05', 'Energy': 0}, {'Time': '06', 'Energy': 0}, {'Time': '07', 'Energy': 28525}, {'Time': '08', 'Energy': 49332}, {'Time': '09', 'Energy': 745}, {'Time': '10', 'Energy': 0}, {'Time': '11', 'Energy': 0}, {'Time': '12', 'Energy': 0}]}], 'IsSuccess': True, 'Message': 'Success', 'StatusCode': 'Success'}
2021-09-06 11:34:05 DEBUG (MainThread) [toshiba_ac.device_manager] Power consumption for devices: {'4b859d0a-23b2-456b-95fc-d401620f24d7': ToshibaAcDeviceEnergyConsumption(energy_wh=78602, since=datetime.datetime(2020, 12, 31, 23, 0, tzinfo=datetime.timezone.utc))}
2021-09-06 11:34:05 DEBUG (MainThread) [toshiba_ac.device] [Office] Energy consumption: ToshibaAcDeviceEnergyConsumption(energy_wh=78602, since=datetime.datetime(2020, 12, 31, 23, 0, tzinfo=datetime.timezone.utc))
```

We have a log saying that device doesn't support energy and after that we see that the device updated it's energy information.

`device.ac_energy_consumption` will be always `None` in `async_setup_entry` as energy consumption is fetched in the background - it's not available right away.

I have changed this in toshiba-ac 0.1.10 and submitted #26

**Comment by haseat** [comment]
With the latest version 2021.9.1 everything works fine for me.

**Comment by h4de5** [comment]
great.
