### ISSUE TITLE
2021.9.1 does not load in HA

### ISSUE THREAD

**Issue by chrisandsally** [h4de5/home-assistant-toshiba_ac#27]
Just upgraded from prior release, and does not show within HA. Tried reinstall, rebooting, nothing. Any pointers?

**Comment by m2k93** [comment]
The same thing since the HA update sees only one device out of the 7. With the old version no problem

**Comment by h4de5** [comment]
this seems to be a problem in the updated API upstream. I created a PR there. will update tomorrow

**Comment by chrisandsally** [comment]
Thank you folks!. I am unsure if this matters but, my AC unit does not have energy monitoring as not available on the Toshiba APP. Unless you have worked out how to report energy with your code.  But the prior version with outdoor temp sensor was amazing.  I hope the above fix from h4de5 will work, just wanted to help in a very limited capacity!

**Comment by Didier3L** [comment]
> 
> 
> La même chose puisque la mise à jour HA ne voit qu'un appareil sur les 7. Avec l'ancienne version pas de problème

+1

**Comment by Didier3L** [comment]
Hello
Update in 2021.9.2
Two out of four recognized climations

**Comment by h4de5** [comment]
this should be fixed with version 2021.9.2

**Comment by chrisandsally** [comment]
Yes, now loads under 2021.9.2 Thank you!

Outdoor Sensor reports **Entity is non-numeric: sensor.studio_outdoor_temperature** and does not load?
