### ISSUE TITLE
Credential

### ISSUE THREAD

**Issue by Mik-3DXT** [h4de5/home-assistant-toshiba_ac#28]
Where can i put the credential of toshiba app after installed the repository?
Thanks

**Comment by h4de5** [comment]
Open Home-assistant > go to settings > Integrations > Add Integration > Search for "toshiba"

![image](https://user-images.githubusercontent.com/6115324/132494437-94c43f18-8202-4853-aa15-0970955e5872.png)

**Comment by Mik-3DXT** [comment]
Thanks
