### ISSUE TITLE
2021.9.2 Two out of four recognized device

### ISSUE THREAD

**Issue by Didier3L** [h4de5/home-assistant-toshiba_ac#29]
Hello
Update in 2021.9.2
Two out of four recognized device
back to version 2021.8.8

**Comment by h4de5** [comment]
thanks for the information. are there any further warnings or errors shown in the log? i do not recall that the device listing process would have changed.

**Comment by Didier3L** [comment]
`Logger: homeassistant.components.sensor
Source: custom_components/toshiba_ac/sensor.py:40 
Integration: Capteur (documentation, issues) 
First occurred: 21:44:51 (1 occurrences) 
Last logged: 21:44:51

Error while setting up toshiba_ac platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/toshiba_ac/sensor.py", line 40, in async_setup_entry
    devices: List[ToshibaAcDevice] = await device_manager.get_devices()
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device_manager.py", line 107, in get_devices
    device = ToshibaAcDevice(
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 88, in __init__
    self.load_supported_merit_features(merit_feature, ac_model_id)
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 114, in load_supported_merit_features
    floor, _, cdu_silent, pure_ion, fireplace, heating_8c, _, _ = struct.unpack('????????', bytes.fromhex('0' + '0'.join(f'{merit_byte:08b}')))
ValueError: non-hexadecimal number found in fromhex() arg at position 1

`

**Comment by Didier3L** [comment]
Logger: azure.iot.device.common.handle_exceptions
Source: /usr/local/lib/python3.9/site-packages/azure/iot/device/common/handle_exceptions.py:28 
First occurred: 21:47:29 (2 occurrences) 
Last logged: 21:51:01

Exception caught in background thread. Unable to handle.

**Comment by Didier3L** [comment]
Logger: azure.iot.device.common.handle_exceptions
Source: /usr/local/lib/python3.9/site-packages/azure/iot/device/common/handle_exceptions.py:29 
First occurred: 21:47:29 (2 occurrences) 
Last logged: 21:51:01

["azure.iot.device.iothub.sync_handler_manager.HandlerManagerException: HandlerManagerException('HANDLER (CLIENT_EVENT): Error during invocation') caused by KeyError('f08e1750-67e6-4670-92f9-ed5201ac16be')\n"]
["azure.iot.device.iothub.sync_handler_manager.HandlerManagerException: HandlerManagerException('HANDLER (CLIENT_EVENT): Error during invocation') caused by KeyError('xxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxx')\n"]

**Comment by Didier3L** [comment]
Logger: homeassistant.components.climate
Source: custom_components/toshiba_ac/climate.py:64 
Integration: Thermostat (documentation, issues) 
First occurred: 21:58:01 (1 occurrences) 
Last logged: 21:58:01

Error while setting up toshiba_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/toshiba_ac/climate.py", line 64, in async_setup_entry
    devices = await device_manager.get_devices()
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device_manager.py", line 107, in get_devices
    device = ToshibaAcDevice(
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 88, in __init__
    self.load_supported_merit_features(merit_feature, ac_model_id)
  File "/usr/local/lib/python3.9/site-packages/toshiba_ac/device.py", line 114, in load_supported_merit_features
    floor, _, cdu_silent, pure_ion, fireplace, heating_8c, _, _ = struct.unpack('????????', bytes.fromhex('0' + '0'.join(f'{merit_byte:08b}')))
ValueError: non-hexadecimal number found in fromhex() arg at position 1

**Comment by h4de5** [comment]
@KaSroka  it seems the merit feature may not always be 4 characters long here:
https://github.com/KaSroka/Toshiba-AC-control/blob/c6df0ef6547db6bbf10266fefeb8a422bd8266c9/toshiba_ac/device.py#L104

        merit_byte, _ = struct.unpack('bb', bytes.fromhex(merit_feature_hexstring))

which leads to the above error.

**Comment by Didier3L** [comment]
hoping you find the solution

**Comment by KaSroka** [comment]
@Didier3L in logs for the problematic device you should have something like this:
```
... merit_feature='7c03' ...
```
can you share the value you have here, especially for the devices that are not working?

**Comment by Didier3L** [comment]
Unrecognized units are
Chambre Clara
Chambre Parents
```

2021-09-14 18:25:14 DEBUG (MainThread) [toshiba_ac.device_manager] 
Found devices: [ToshibaAcDeviceInfo(ac_id='xxxxx-xxxxx-xxxxx-xxxxx-xxxxx',
ac_unique_id='xxxxx-xxxxx-xxxxx-xxxxx-xxxxx',
ac_name='Salon',
initial_ac_state='3142193131640010191cfe0200001001010000',
firmware_version='3.2.01',
merit_feature='3c00',
ac_model_id='2'),
ToshibaAcDeviceInfo(ac_id='95e4eb0c-3a96-4927-9edc-52a63747fc4d',
ac_unique_id='xxxxx-xxxxx-xxxxx-xxxxx-xxxxx',
ac_name='Chambre Alice',
initial_ac_state='3142154131640010191cfe0b00001002000000',
firmware_version='3.2.01',
merit_feature='3c00',
ac_model_id='2'),
ToshibaAcDeviceInfo(ac_id='7f7ff1f5-4e0d-40b9-9ed1-7d43533691be',
ac_unique_id='xxxxx-xxxxx-xxxxx-xxxxx-xxxxx',
ac_name='Chambre Clara',
initial_ac_state='3042143531643010131efe0b00001002000000',
firmware_version='3.2.01',
merit_feature='ac00',
ac_model_id='2'),
ToshibaAcDeviceInfo(ac_id='9ac813ff-ad7e-481a-a4e2-aa7fa5ec38c2',
ac_unique_id='xxxxx-xxxxx-xxxxx-xxxxx-xxxxx',
ac_name='Chambre Parents',
initial_ac_state='3042174131640010161cfe0b00001002010000',
firmware_version='3.2.01',
merit_feature='3c00',
ac_model_id='2')]

```

**Comment by Didier3L** [comment]
I have good news
I deleted the Toshiba plugin and did an installation again
All 4 units are recognized
