### ISSUE TITLE
Outdoor temperature always unknown in HA

### ISSUE THREAD

**Issue by Sabreu** [h4de5/home-assistant-toshiba_ac#30]
With Toshiba Polar35 I have this problem that outdoor temp is always unknown

AC Indoor unit model: RAS-35J2KVSG-ND
AC outdoor unit model: RAS-35J2AVSG-ND

in logs I can see that the first time indoor temp is shown correctly outdoor is unknown

[toshiba_ac.device] [AC_xxxx] Current state: AcStatus: ON, AcMode: HEAT, AcTemperature: 22, AcFanMode: HIGH, AcSwingMode: NOT_USED, AcPowerSelection: POWER_100, AcMeritBFeature: OFF, AcMeritAFeature: OFF, AcAirPureIon: OFF, AcIndoorAcTemperature: 25, AcOutdoorAcTemperature: UNKNOWN, AcSelfCleaning: OFF

Then the next logs are showing also outdoor temp but it is never updated to HA. HA always shows outdoor temp as unknown

[toshiba_ac.device] [AC_xxxx] Current state: AcStatus: ON, AcMode: HEAT, AcTemperature: 21, AcFanMode: HIGH, AcSwingMode: NOT_USED, AcPowerSelection: POWER_100, AcMeritBFeature: OFF, AcMeritAFeature: OFF, AcAirPureIon: OFF, AcIndoorAcTemperature: 25, AcOutdoorAcTemperature: 8, AcSelfCleaning: OFF

![kuva](https://user-images.githubusercontent.com/1567864/133131540-6a6cb14f-134c-4ec6-b62a-53b1f018c666.png)

Also the hearbeat shows oTemp
[toshiba_ac.device] [AC_xxxx] AC heartbeat from AMQP: {'iTemp': 21, 'oTemp': 8, 'fcuTcTemp': 255, 'fcuTcjTemp': 255, 'fcuFanRpm': 255, 'cduTdTemp': 255, 'cduTsTemp': 255, 'cduTeTemp': 255, 'cduCompHz': 255, 'cduFanRpm': 255, 'cduPmvPulse': 255, 'cduIac': 255}

**Comment by KaSroka** [comment]
It looks like outdoor temp sensor is registered on wrong callback: https://github.com/h4de5/home-assistant-toshiba_ac/blob/main/custom_components/toshiba_ac/sensor.py#L224

**Comment by h4de5** [comment]
yes - I got that one too. I hope I can upload the fix for this tonight.
