### ISSUE TITLE
2021.9.3 Maybe not an issue - Outdoor Temp Sensor Question

### ISSUE THREAD

**Issue by chrisandsally** [h4de5/home-assistant-toshiba_ac#31]
Outdoor Temperature works when unit 'on', but as we know when 'off' it shows up as unknown (Within the App). Under developer tools in HA it gives a value of null, which seams reasonable.

I created a gauge within HA and looks great when "ON" but shows entity is non-numeric when "OFF" How can I still show the gauge without it looking like a missing entity. Is this a HA thing or a integration enhancement?

![Screenshot 2021-09-15 at 22 25 48](https://user-images.githubusercontent.com/89684974/133512218-205acb29-ea57-41b7-946b-4b219d1d87d4.png)

**Comment by h4de5** [comment]
note sure if gauge would be the right entity for a temperature.
It will now return an empty string, which no longer triggers your error. but it will be shown as 0°C in a gauge.

**Comment by KaSroka** [comment]
@h4de5 I think the better solution would be to report that sensor is unavailable - it will work with any integration, what do you think?

**Comment by chrisandsally** [comment]
@KaSroka If reported as unavailable would that cause an entity failure? If not then seams a good way to go. Because 0°C is a valid number and may cause issues with automations that may use that to trigger a heater or something.

**Comment by KaSroka** [comment]
@h4de5 it should just show gauge or other widget to show unavailable. We may check it easily

**Comment by h4de5** [comment]
unavailable is possible, but i would show a similar message that you already had. also automations looking for 0 ahould not trigger, because the value  reported is empty ("").it is just the widget that displays it as 0°c

**Comment by KaSroka** [comment]
Still, I think it's a proper way and we may use both - return "" but also return available as false

**Comment by Cecchellone** [comment]
How does it behave inside Home Assistant if you return `None` instead of the `""`?

**Comment by h4de5** [comment]
i believe None would show similar to the initial screenshot.
