### ISSUE TITLE
Lost...

### ISSUE THREAD

**Issue by mycanaletto** [h4de5/home-assistant-toshiba_ac#35]
Hello,
At the beginning this integration was working well (2/3 months ago).

Then I realized that the air conditioner seems to be lost from time to time and the temperature is no longer updated in HA (and I'm not talking about the outdoor sensor for which the return is very random ...).

I set up a monitoring of the IP of the air conditioner and on this side it is always OK.

I removed the integration and reinstalled without success.

There, for example, immediately I have 23 in the Toshiba application and 21 in Home Assistant... So the temperature of the internal sensor does not go back well to HA which can not do its job ...

**Comment by h4de5** [comment]
Hi,
this is rather hard to debug. the integration does not take the current states (like temperature) from the device itself, but rather from the toshibas online service:

https://toshibamobileservice.azurewebsites.net/api/AC/GetCurrentACState
(see: https://github.com/KaSroka/Toshiba-AC-control/blob/a3e2e1cea15f23aac65e557c9942ce4845ba7761/toshiba_ac/http_api.py#L49)

can you try out the examples on that repo? they work without home-assistant.

**Comment by h4de5** [comment]
please reopen with more information if still an issue.
