### ISSUE TITLE
Failed to load configuration flow: undefined

### ISSUE THREAD

**Issue by galamarco** [h4de5/home-assistant-toshiba_ac#46]
Hello,
I'm writing to report a bug for which the downloaded integration cannot be configured.

I download Toshiba AC, from HACC 2022.2.3, on my HA 2022.3.8, I reboot and I found it in integration list.
![Integration](https://www.webg.it/images/articoli/2022-03/Screenshot_85.png)

I click on it and it is loading for a very long time...

![Integration](https://www.webg.it/images/articoli/2022-03/Screenshot_83.png)

After some minute I can see an error "Failed to load configuration flow: undefined" and installation stop.

![Integration](https://www.webg.it/images/articoli/2022-03/Screenshot_84.png)

In HA log I don't have error with "thoshiba". I think there are some issue in installation code. 
Can you check please?

**Details**
HA version: core-2022.3.8
Type: Home Assistant OS
Host OS: Home Assistant OS 7.5
Supervisor version: supervisor-2022.03.5
Docker: 20.10.9

Best regards
Marco

**Comment by h4de5** [comment]
can you check if you find anything related to that errors in your logs? I just tested it with a fresh install and it worked fine for me.

**Comment by YannikNielsen** [comment]
I had the same issue. I just went to the integration in HACS, clicked redownload, restarted HA and then it worked.

**Comment by h4de5** [comment]
please reopen with more information if still an issue.
