### ISSUE TITLE
How to use temperature in automations?

### ISSUE THREAD

**Issue by phoenix-anasazi** [h4de5/home-assistant-toshiba_ac#47]
Hello,

this integration works perfectly for me inside HA, thanks for your work. But I would like to use it in some automations. And at least for me it is not possible to set the temperature from automations. I can only change hvac_mode and preset_mode. Am I missing something (HA newb)? Thanks for your help.
![grafik](https://user-images.githubusercontent.com/63506636/162200326-9d0bf10a-a365-403b-b596-01199c8411fd.png)
Regards

**Comment by h4de5** [comment]
you use the generic climate.set_temperature service - and select your climate entity as target.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/6115324/162280532-6a06f288-9de7-449f-988f-79cfbf84375b.png">
