### ISSUE TITLE
Use AC Toshiba in automation 

### ISSUE THREAD

**Issue by dnamat88** [h4de5/home-assistant-toshiba_ac#50]
When i try to use one of my Toshiba AC in automation, i cannot set the entity. When i click, it reset the Field.
How can i do?
Home assistant core, last update.

Ps: i can use AC with dashboard

**Comment by h4de5** [comment]
if you want to change something in the device, you usually use "call service" and then e.g.: "climate: set HVAC mode", select your toshiba AC as entity and the mode you want to set.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/6115324/172259239-052e9e40-b3ac-4367-b8a9-e3ab8f25f2a5.png">

**Comment by h4de5** [comment]
alternativly you should see the device and set it from there as well:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/6115324/172259393-59c817e6-0bc2-4f40-9e32-837161e75d6c.png">
