### ISSUE TITLE
Possibly multiple Toshiba AC endpoints?

### ISSUE THREAD

**Issue by GoTTi74** [h4de5/home-assistant-toshiba_ac#53]
I have installed the custom integration in HA. However, when I try to configure it and enter my (Toshiba) userName & PW, I’m getting an “Invalid Authentication”. I can ensure that it’s not a UserName/PW. I even logged out of the Toshiba AC app and copied/pasted UserName & PW into the App and HA. The App authenticates but HA doesn’t. I could imagine that Toshiba uses different endpoint for their App depending on the region. Not sure if this could be configured in the component somewhere?

BTW: I’m in the US and the (iOS) App is called “Toshiba AC NA”, whereas “NA” most probably stands for North America, which would indicate that there are different Apps with different endpoints…

Any idea where/how to adapt to different regions?

**Comment by h4de5** [comment]
we got this question on the HA forum as well: https://community.home-assistant.io/t/toshiba-home-ac-control/137698/121

it seems toshiba distributes their AC devices with a different app in the US. because I do not have that app or their source, I cannot confirm that it is just a different endpoint or a different API altogether.

for now, toshiba ACs distributed in the US are not supported until someone analyzed and reverse engineered the IOs App and provide necessary insights.

**Comment by GoTTi74** [comment]
Thank you Andi

After further research, I found that the App for Toshiba ACs sold in North America is made by Midea Corp., which owns Toshiba, and that there’s a working integration in HACS (Midea Smart Aircon). This integration has a different approach as it connects directly to the AC in the local network. 

All good for me :-)

>

**Comment by h4de5** [comment]
just to have it all in one issue:

checkout the HACS repository for midea: 

https://hacs.xyz/docs/repositories/integration/mac_zhou_midea_ac_py

**Comment by gnmerritt** [comment]
For anyone following these breadcrumbs, the repo linked above doesn't seem to be stable/working via HACS right now. 

I had better luck with https://github.com/georgezhao2010/midea_ac_lan which is on HACS as "Midea AC LAN" here https://hacs.xyz/docs/repositories/integration/georgezhao2010_midea_ac_lan

**Comment by tomchapin** [comment]
The Midea smart home app appears to only support a single Toshiba window air conditioner (not mine, which is a portable A/C).

Has anyone figured out how to get the "Toshiba AC NA" app and the latest Toshiba air conditioners working with home assistant (or even via just some kind of direct network control)?

**Comment by matthewCmatt** [comment]
Should a note on this be added to the main [README](https://github.com/h4de5/home-assistant-toshiba_ac?tab=readme-ov-file#compatible-devices)? Seems like it could be a common issue.
