### ISSUE TITLE
hvac_action is incorrect

### ISSUE THREAD

**Issue by tetienne** [h4de5/home-assistant-toshiba_ac#55]
Hi, looking at the code, I noticed the `hvac_action` property [behaves](https://github.com/h4de5/home-assistant-toshiba_ac/blob/main/custom_components/toshiba_ac/climate.py#L229) like `hvac_mode`.

But `hvac_action` must be the current running hvac operation, which is not the same than the selected mode. 

Within the official application, I don’t see any information relative to this. To test, it’s quite simple, I have just set the fresh mode and set the target temperature to 30 while the current temperature was 23.

If there is no solution to retrieve the current operation, do you agree we remove this wrong property ?

**Comment by h4de5** [comment]
is this reason for #56  and #57  ?

**Comment by tetienne** [comment]
About the swing mode, I just fixed it. It should be OK once you will merged my last pr.

But this is out of topic here 😀

Now you have get back your unit you will be able to see what I mean by invalid hvac_action.

Set your unit in Heat mode. Set the target temperature upper the current temperature, so the unit should not do anything. Currently, this component reports Heating instead of Idle. So IMO we must remove this property except if we can get the true state from Toshiba API.

**Comment by h4de5** [comment]
i just tested this one: for my device it does not go into idle mode. e.g. if I change from cooling to heating and set the target temperature to 22°C (while it has 24° inside and 30° outside as you suggested) it briefly stops for a minute. i think this is just to switch to the different mode. but after that time, it starts heating - regardless of the target/current temperature. 
same is for auto or cooling.

I could change the hvac_action based on a comparisson of current and target temp here - https://github.com/h4de5/home-assistant-toshiba_ac/blob/4558e7c930aa05973da391a9138fe1d113f22bea/custom_components/toshiba_ac/climate.py#L235
but this would not reflect the real state as you said. 

I created an issue in the API for this https://github.com/KaSroka/Toshiba-AC-control/issues/31

**Comment by h4de5** [comment]
I also think this one is done already.
