### ISSUE TITLE
After updating from 2022.4.1 to 2022.6.15

### ISSUE THREAD

**Issue by chrisandsally** [h4de5/home-assistant-toshiba_ac#63]
Firstly thank you to all contributors new and old for keeping this integration updated and current. I am subscribed to the integration and although not a programmer happy to test and report and findings.

On this version (.15) I can only turn the unit On and Off to each mode. Auto/Fan/Cool/Heat etc

The internal /outdoor temp, presets, swing mode are all non responsive. They were all working under 2022.4.1

Happy to test anything as I know can revert back if required.

**Comment by tetienne** [comment]
Hi, can you please install again the component using HACS targeting the main branch and not a specific version? It should fix your issues

**Comment by chrisandsally** [comment]
Installed and all working (Temp In/Out. Target temp, Operation, preset, Fan Mode) bar Swing Mode. It is constantly swinging! When you select it immediately changed back to off but unit keeps swinging.

**Comment by tetienne** [comment]
Great! About the swing, it was the case with the 2022.4 version?

**Comment by tetienne** [comment]
Nevermind, I found the issue. I will do the fix asap

**Comment by chrisandsally** [comment]
I was about to downgrade to double check, so I'll hang fire

**Comment by tetienne** [comment]
Can you please download https://github.com/tetienne/home-assistant-toshiba_ac/archive/refs/heads/fix/climate/swing.zip, extract it, and copy `custom_components/toshiba_ac` on your local `custom_components/toshiba_ac` and tell me if the swing mode is now well OK?

**Comment by chrisandsally** [comment]
Hi, Yes, that's got it! all back. Thank you :) So does this mean we are all compliant against any depreciated code?

**Comment by tetienne** [comment]
I think so. But, HA is moving so fast there is already coming depreciated properties with the next HA release.

I will continue to clean this component until we can integrate Core repository.

**Comment by chrisandsally** [comment]
Wow. Thanks for supporting this integration. Amazing work.
