### ISSUE TITLE
Current temperature doesn't update

### ISSUE THREAD

**Issue by benvanmierloo** [h4de5/home-assistant-toshiba_ac#65]
Quick question. Does the integration periodically update the current temperature? When initially starting (or reloading) the integration, all current temperature values are correct, but they don't change afterwards for me. Am I missing something?

**Comment by h4de5** [comment]
it definitively should and it does for me. do you get any messages about the toshiba integration in the logs?

**Comment by benvanmierloo** [comment]
I'll monitor some more, i'll close the ticket for now. Thanks for the response!

**Comment by benvanmierloo** [comment]
Sorry I still don't have logfiles, but I really do think something is not updating the way it should. Both screenshots below are taken at the same time. The Toshiba app on the phone displays the correct current temperatures, while home assistant shows the values when the AC was turned on (ca 30 minutes ago). Seems like there is no update in the meanwhile while the AC is on. If I change one of the AC's through home assistant (e.g. different operation mode, different set temperature, ...), then instantly the values of all AC's update with the correct values.
Also when one of the AC's goes from operation mode X to Y, everything also updates. This happens for example when the set temperature is reached and the operation switches to idle on its own.

Hope this sheds some light on the issue. 

![image](https://user-images.githubusercontent.com/3785514/180616278-4408f1f6-e5f5-494d-bbb5-9767639e1fd4.png)
![image](https://user-images.githubusercontent.com/3785514/180616292-83cc9e4d-3c33-4aae-9312-25752a88f166.png)

**Comment by h4de5** [comment]
do you have the same issue when you use the Api directly? https://github.com/KaSroka/Toshiba-AC-control

**Comment by benvanmierloo** [comment]
I was reading through the code (of the API), and I think I found the answer.. Seems like the update interval is 30 minutes. Next time I will wait 31 minutes and see if the values update :-)

```
class ToshibaAcDevice:
    STATE_RELOAD_PERIOD_MINUTES = 30
```

```
    async def periodic_state_reload(self) -> None:
        while True:
            await async_sleep_until_next_multiply_of_minutes(self.STATE_RELOAD_PERIOD_MINUTES)
```

Thanks for the help!
