### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by marzzed** [h4de5/home-assistant-toshiba_ac#69]
uninstalled, reinstalled.
takes my credentials for toshiba but all it reports is the outside temp. 
no controls.
Toshiba Haori 25

**Comment by marzzed** [comment]
since one of the last messages says 
"now they are working both fine for me"
I dont know if its still a problem for everyone else. Thats why I posted

**Comment by h4de5** [comment]
I see - i have not yet updated the firmware of my ac unit (or my android app) so the HA integration is still running for me.
I don't know what happens after the deadline or when I do update it.

did you do the toshiba update? android app or the firmware?

**Comment by marzzed** [comment]
Not sure i wich order but the Toshiba to 2.0
and IOS to 3.4

it worked until a restart of HA I think.

/Martin

**Comment by marzzed** [comment]
Latest HA update 2022.07 restored my controls. Lets see if it lasts

**Comment by h4de5** [comment]
closing in favour of #72
