### ISSUE TITLE
Username/Password

### ISSUE THREAD

**Issue by Rbanyai1** [h4de5/home-assistant-toshiba_ac#70]
I load through HACS then reboot load the integration it asks for my user name and password just like the app. I enter and it fails. I deleted my account with Toshiba tried different email accounts nothing. I can logout of the app and login with no problems. I also tried my email as well and just the username. Help please Thank you

**Comment by h4de5** [comment]
please read: https://github.com/h4de5/home-assistant-toshiba_ac/issues/45#issuecomment-1153825833
