### ISSUE TITLE
Integration no longer compatible after Firmware Update to 4.x

### ISSUE THREAD

**Issue by h4de5** [h4de5/home-assistant-toshiba_ac#72]
there have been several issues on that topic: #68 #69 #71 - to easier manage the discussion and a possible solution I will close those issues in favor of this one.

**Toshiba announced a major change in their app and possibly also their backend**

<img src="https://user-images.githubusercontent.com/6115324/179025616-bcf66f7c-cb2c-4531-a10c-73458d392ee1.png" width="250">
screenshot taken from version 3.2 of <a href="https://play.google.com/store/apps/details?id=com.toshibatctc.SmartAC">toshiba home AC</a>

They claim that the end date of the "legacy" version (<=3.2) will no longer work after 14th of July. At least for my device (RAS-18PKVSG-E) this is not the case - I did not do the firmware nor the app update, and it keeps working - at least for now.

I have had a look at the new version of the app (see: https://github.com/h4de5/home-assistant-toshiba_ac/issues/68#issuecomment-1172667406) and currently I am not able to reverse engineer it. Unless I can find a way to do this, or there is an update of the underlying python package (https://github.com/KaSroka/Toshiba-AC-control) which is used to communicate with the server behind the AC unit, **we may be out of luck**.

This means if you have done the firmware update, you may no longer be able to control your AC unit via Home-Assistant. And I cannot do much about it. Some users claim, that a HA restart combined with a cold start of the AC unit, re-enables access, but this may depend on the AC unit itself.

If you are affected by that issue, you can simple hit the subscribe button on the right to stay informed. Please leave the comments only for possible solutions.

Best regards

**Comment by tomitomas** [comment]
on my side I just had a new issue : 
`Fatal error : Cannot connect to host toshibamobileservice.azurewebsites.net:443 ssl:default [Name or service not known]`

so it looks like a lot of changes have been performed by Toshiba ... :(

**Comment by glowaa** [comment]
The hostname toshibamobileservice.azurewebsites.net has no longer DNS record.

Cannot connect to host toshibamobileservice.azurewebsites.net:443 ssl:default [Name does not resolve]

After I manualy set IP 20.86.215.67 to toshibamobileservice.azurewebsites.net is another error.

Cannot connect to host toshibamobileservice.azurewebsites.net:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'toshibamobileservice.azurewebsites.net'. (_ssl.c:997)")]

**Comment by h4de5** [comment]
> on my side I just had a new issue : `Fatal error : Cannot connect to host toshibamobileservice.azurewebsites.net:443 ssl:default [Name or service not known]`
> 
> so it looks like a lot of changes have been performed by Toshiba ... :(

great.. in this case, the integration is **definitely broken now** - I just tested mine again and it does no longer work as well. last connection was done today at midnight.

**Comment by glowaa** [comment]
I have snnifed new DNS name address - mobileapi.toshibahomeaccontrols.com but I dont know where it replace in toshiba_ac files.

**Comment by tomitomas** [comment]
> https://mobileapi.toshibahomeaccontrols.com

I just gave a try, and it looks like it's working for me !

**Comment by glowaa** [comment]
where You change this URL?

**Comment by tomitomas** [comment]
I'm using it by my side, not within HA

**Comment by dario-brombal** [comment]
I have 4 Haori units, everything updated (adapter fw 2.0, app version 3.4) and still working in HA (for now...).

If not able to disassemble the code you may try sniffing packets; probably you should put something between the app and their servers to decode messages (something like a Man-in-the-middle attack, self certifying your "evil" gateway, and replying request to toshiba servers)...

just my 2 cents

Dario

**Comment by KaSroka** [comment]
@h4de5 it was more than that. For merit B features there seems to be a new value of `1` reported but there is nothing about it in disassembled sources of the 3.4.0 APK (I've managed to unpack it using [this](https://github.com/jakev/xamarin-assembly-store-unpack/blob/master/unpack-store.py) on blob file and then modified for python3 version of [this](https://github.com/securitygrind/lz4_decompress/blob/main/lz4_decompress.py) to unpack `dll`, after those steps you can proceed with `ILSpy` as normal) It should be fixed in [v0.3.0](https://github.com/KaSroka/Toshiba-AC-control/releases/tag/v0.3.0)

**Comment by h4de5** [comment]
see latest beta release: https://github.com/h4de5/home-assistant-toshiba_ac/releases

**Comment by gmarongiu71** [comment]
Today I can't login
Sorhai edge fw 4.0

**Comment by zjonesz** [comment]
> see latest beta release: https://github.com/h4de5/home-assistant-toshiba_ac/releases

Getting error
" This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant."

**Comment by tetienne** [comment]
> see latest beta release: https://github.com/h4de5/home-assistant-toshiba_ac/releases
> 
> 
> 
> 

Hi @h4de5 you didn't include the latest version of the lib on this release.

**Comment by glowaa** [comment]
I removed old version and make clean install 2022.7.0-beta with HACS
Error with old URL still occur.
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host toshibamobileservice.azurewebsites.net:443 ssl:default [Name does not resolve]

**Comment by h4de5** [comment]
> > see latest beta release: https://github.com/h4de5/home-assistant-toshiba_ac/releases
> 
> Getting error " This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant."

i have seen this report before, not sure if it was you. there should be a normal UI configuration available:
![image](https://user-images.githubusercontent.com/6115324/179682374-63839c76-c992-4de1-922c-0edabc3eb618.png)
![image](https://user-images.githubusercontent.com/6115324/179682329-a4a37820-81ac-4d69-bacf-3b14aa581ea2.png)


> > see latest beta release: https://github.com/h4de5/home-assistant-toshiba_ac/releases
> 
> Hi @h4de5 you didn't include the latest version of the lib on this release.

I just checked - the manifest says: `"requirements": ["toshiba-ac==0.3.0"]` which is referring to the python package: https://pypi.org/project/toshiba-ac

and there the new url is also included: `BASE_URL = "https://mobileapi.toshibahomeaccontrols.com"`

**Comment by KaSroka** [comment]
@h4de5 but the 2022.7.0-beta is released from master which does not have manifest changes. Also my lib was restructured a bit so some alignment is probably needed.

**Comment by tetienne** [comment]
@KaSroka Thx for your quick fix. It works perfectly with HA: https://github.com/h4de5/home-assistant-toshiba_ac/pull/75

**Comment by tetienne** [comment]
If you want to try my fix, download the [zip](https://github.com/tetienne/home-assistant-toshiba_ac/archive/refs/heads/fix/toshiba-endpoint.zip), extract the `toshiba_ac` folder and move it to your `custom_components` folder.

**Comment by Michael0yodi** [comment]
> If you want to try my fix, download the [zip](https://github.com/tetienne/home-assistant-toshiba_ac/archive/refs/heads/fix/toshiba-endpoint.zip), extract the `toshiba_ac` folder and move it to your `custom_components` folder.

Works great!

**Comment by gmarongiu71** [comment]
> If you want to try my fix, download the [zip](https://github.com/tetienne/home-assistant-toshiba_ac/archive/refs/heads/fix/toshiba-endpoint.zip), extract the `toshiba_ac` folder and move it to your `custom_components` folder.

For me now work... thanks

**Comment by glowaa** [comment]
> If you want to try my fix, download the [zip](https://github.com/tetienne/home-assistant-toshiba_ac/archive/refs/heads/fix/toshiba-endpoint.zip), extract the `toshiba_ac` folder and move it to your `custom_components` folder.

Its working, thanks.

**Comment by crolaser** [comment]
work like charm .thanks

**Comment by h4de5** [comment]
> @h4de5 but the 2022.7.0-beta is released from master which does not have manifest changes. Also my lib was restructured a bit so some alignment is probably needed.

i see. only the release file zip uses correct branch. but not the source. does this mean the HACS integration always uses the source.tar.gz? 

i need to have another look on the release stuff tomorrow.

**Comment by tetienne** [comment]
@h4de5 HACS does not look at all the release attachment. It directly checkout the repository with the given tags. So here as you tag the latest commit of the main branch with 2022.7.0-beta, hacs checkout this one.

See my suggestion to clean your release process: https://github.com/h4de5/home-assistant-toshiba_ac/pull/76

**Comment by h4de5** [comment]
There is a new release including the updates fom @tetienne and @KaSroka.
I leave the issue open for now, until some positive feedback :)

**Comment by dario-brombal** [comment]
Here everything is back working with 2022.7.1. This morning wasn't.

The only thing I noticed Is AC telling "inactive" while it's working when temperature Is as set point, not working like this before

**Comment by h4de5** [comment]
> Here everything is back working with 2022.7.1. This morning wasn't.
> 
> The only thing I noticed Is AC telling "inactive" while it's working when temperature Is as set point, not working like this before

thats right. this is something that was not release before. I tested some stuff, it should return idle state, so you can check in automations for this. as the AC unit does not go into idle mode, this does not reflect reality. Ill create a new issue for this.

**Comment by wltng** [comment]
Thanks all for fixing this issue so quickly!
I just ordered a second toshiba AC unit and was afraid I wouldn't be able to control it with HA.
It all seems fine now (RAS-B13J2KVSG, Kazumi)!

**Comment by h4de5** [comment]
after a HA restart my old installation stopped working as well. so i upgraded everything and it seems to be all good now. thanks for all your support

**Comment by peterblom23** [comment]
Amazing guys!!!! Daily user of the integration you created! Where can I buy you a beer?

**Comment by h4de5** [comment]
> Amazing guys!!!! Daily user of the integration you created! Where can I buy you a beer?

I have forward all thank you notes to those guys: @KaSroka and @tetienne 
(I merely clicked on merge ;) )
