### ISSUE TITLE
Toshiba AC integration stop working

### ISSUE THREAD

**Issue by galamarco** [h4de5/home-assistant-toshiba_ac#74]
Hello,
today all devices stop working are uncontrollable by Toshiba AC integration.
The error log shows "they are currently not available"

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:130
First occurred: 18 luglio 2022 19:41:05 (15 occurrences)
Last logged: 06:41:54

Unable to find referenced entities climate.clima_salotto or it is/they are currently not available
Unable to find referenced entities climate.clima_letto or it is/they are currently not available
Unable to find referenced entities climate.clima_cucina or it is/they are currently not available
```
![image](https://www.webg.it/images/articoli/2022-07/Screenshot_19.png)
![image](https://www.webg.it/images/articoli/2022-07/Screenshot_20.png)

Thoshiba device firmware: Firmware: 4.0.00
Home Assistant 2022.7.5
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.1 - latest

**Comment by tetienne** [comment]
Hi, this is a dup of https://github.com/h4de5/home-assistant-toshiba_ac/issues/72

**Comment by galamarco** [comment]
I found this text in log, but I don't know if you have anything to do with the problem:

`2022-07-19 10:10:28 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration toshiba_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Comment by h4de5** [comment]
see #72
