### ISSUE TITLE
config

### ISSUE THREAD

**Issue by stehuz** [h4de5/home-assistant-toshiba_ac#78]
Hi, how config should look like I install it via HACS as well added via integrations. But where and how I can add it to dashboard. Is creation of some custom component needed? I can see toshiba in integration but nothing in devices or entities.Thx

**Comment by h4de5** [comment]
once you added it via the Integration page of HA

see: https://github.com/h4de5/home-assistant-toshiba_ac/issues/72#issuecomment-1188661250

you should see your devices and for each device 1 or 2 entities (one for climate one for the outside temperature)

**Comment by stehuz** [comment]
Unfortunately I can't see any device nor entity. But within toahiba app it works just fine.
Any Idea for troubleshooting? Within common HA logs there is no error.

**Comment by h4de5** [comment]
did you add the integration using the UI?

**Comment by h4de5** [comment]
are you using one of the support apps? (see readme)

**Comment by stehuz** [comment]
Yes, I did it , exactly based on guide :/

**Comment by h4de5** [comment]
I am sorry. I still do not know on which place you are stuck? 

You added the toshiba AC custom component successfully? you should see this in the logs:

> WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration toshiba_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

Once you added the toshiba AC integration to your HA setup - there must be some more logging:

> INFO (MainThread) [custom_components.toshiba_ac.climate] Adding 1 climates

**Comment by stehuz** [comment]
I'm getting that first log, but not that second one. I have integration deployed just fine with my toshiba account credentials. But no device nor entity will come up. I'm using external wifi module for Estia heat pump. Probably I do have combination which is not supported even it works with Toshiba app :/ I don't want to bother you more, once I'll have bit more time I'll try to troubleshoot it more may be to capture and intercept some network traffic to see what's happening there.

**Comment by h4de5** [comment]
you can try to call the API directly. e.g. have a look at the example code in python: 
https://github.com/KaSroka/Toshiba-AC-control/blob/main/samples/toshiba_ac_gui.py

if you are more familiar with other programming languages you can have a look at the very simple php example:

https://gist.github.com/h4de5/7f97db0f4efc265e48904d4a84dab4fb

this will not allow you to control the AC, but at least you should see your linked devices.
