### ISSUE TITLE
Does not work with north amarican version of APP

### ISSUE THREAD

**Issue by theChef613** [h4de5/home-assistant-toshiba_ac#83]
this integration does not work with [TOSHIBA AC NA](https://play.google.com/store/apps/details?id=com.midea.toshiba&hl=en_US&gl=US)
I am unable to login

**Comment by h4de5** [comment]
this is true. see list of supported devices : https://github.com/h4de5/home-assistant-toshiba_ac/issues/45#issuecomment-1153825833

**Comment by mrfixitpa** [comment]
Is there any plans for a working version for Toshiba AC NA? I just purchased two units and thought for sure since they were Alexa/ Google / Wifi that this would have worked with HAAS.

**Comment by mrfixitpa** [comment]
Thank you! I will definitely check this out after work.

**Comment by theChef613** [comment]
I checked this out and works great! thank you!
