### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by hubertron** [h4de5/home-assistant-toshiba_ac#84]
I just downloaded and installed this via HACS and get an Invalid Authentication when trying to log in. I see no error or any output messaging in logs and unable to troubleshoot futher. The login matches the one I use in the app. 

App version is 4.0.4
Home assistant is latest August update.

**Comment by h4de5** [comment]
please check https://github.com/h4de5/home-assistant-toshiba_ac/issues/45#issuecomment-1153825833
