### ISSUE TITLE
Error on adding Toshiba App Integration

### ISSUE THREAD

**Issue by dethorpe** [h4de5/home-assistant-toshiba_ac#86]
Error
Config flow could not be loaded: undefined

What other information can I provide?

**Comment by h4de5** [comment]
does the error come up when you add it through the integration page within HA? so you can already see the toshiba logo?

**Comment by h4de5** [comment]
underneath it is usong the python package https://github.com/KaSroka/Toshiba-AC-control

there are examples where you can try out the connection directly and maybe change the encoding.

**Comment by dethorpe** [comment]
lol Sorry. I wrote "your code" but I meant their code as in Toshiba x_x
------
David-Eric Thorpe
Phone: 234.567.9383
***@***.***

**Comment by h4de5** [comment]
please reopen if still an issue.
