### ISSUE TITLE
Incompatible with daikin_residential integration

### ISSUE THREAD

**Issue by TheAlpiner** [h4de5/home-assistant-toshiba_ac#87]
I do not know if it is this integration or the other one. But i have struggled to get an integration up for a Daikin device i have. After disabling one integration after another everything worked when disabling the Toshiba_AC integration. I have an open issue on the other one:

https://github.com/rospogrigio/daikin_residential/issues/84

I enabled your ingtegration iafter activation of the other one and it seems to work after that. So it might be the initializing process that fails. But i have a lot of integrations and only yours (Toshiba_AC) fails. So my guess is that it is something is wrong with it. I just tought you should know :-)

**Comment by h4de5** [comment]
is the error message similar to #40 ?

**Comment by TheAlpiner** [comment]
Well part of it. i find this line

TypeError: get() takes 1 positional argument but 2 were given

And that error is the same. Så this looks very similar

**Comment by HeroBart** [comment]
@h4de5 this is also related: https://github.com/home-assistant/core/issues/75739
I'd be happy to help as pointed in my comment in above issue, if I can get some pointers on where to look next :)

**Comment by h4de5** [comment]
unfortunatelly I have no idea how to solve this. those integrations (solar edge and daikin) require an older version of the requests python package. therefor the call is not compatible with the version required from our dependency ([toshiba-ac](https://pypi.org/project/toshiba-ac/)). I am not sure on how to solve this from my side, as I can only list the dependencies I need.

**Comment by KaSroka** [comment]
I don't fully understand which lib is conflicting currently.

This is used by "fresh install" of toshiba-ac 0.3.1:
```
aiohttp==3.8.3
aiosignal==1.3.1
async-timeout==4.0.2
attrs==22.2.0
azure-iot-device==2.9.0
certifi==2022.12.7
charset-normalizer==2.1.1
deprecation==2.1.0
frozenlist==1.3.3
idna==3.4
janus==1.0.0
multidict==6.0.4
packaging==23.0
paho-mqtt==1.6.1
PySocks==1.7.1
requests==2.28.2
requests-unixsocket==0.3.0
six==1.16.0
toshiba-ac==0.3.1
typing_extensions==4.4.0
urllib3==1.26.14
yarl==1.8.2
```

**Comment by h4de5** [comment]
its aiohttp i think:
https://github.com/h4de5/home-assistant-toshiba_ac/issues/40#issuecomment-1049267401

**Comment by KaSroka** [comment]
Exactly, both aiohttp and requests are fairly new if not recent versions, so I don't really know where is the problem

**Comment by h4de5** [comment]
no longer installable due to conflicting dependencies - see  #113

**Comment by HeroBart** [comment]
I think if you update everything to the latest version, incompatibilities should be solved. Worth a try!

**Comment by h4de5** [comment]
please reopen if still an issue.
