### ISSUE TITLE
Connection error when using example API

### ISSUE THREAD

**Issue by runbert** [h4de5/home-assistant-toshiba_ac#89]
You are linking to this example code from the main README.md: https://github.com/h4de5/home-assistant-toshiba_ac/tree/keep-http-api/custom_components/toshiba_ac/toshiba_ac_api

When running `py example.py --username XX --password yy` as stated in the documentation (using same credentials as in the iOS app), the application returns the following error: 

`Error occurred: HTTPSConnectionPool(host='toshibamobileservice.azurewebsites.net', port=443): Max retries exceeded with url: /api/Consumer/Login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026A221BF430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Empty Response from API call - check Connection to Toshiba services`

`toshibamobileservice.azurewebsites.net` seems to be down when trying to ping it. Could that be the problem and in that case, which is the new domain to use?

Any other ideas of what might be wrong?

Thanks!

**Comment by h4de5** [comment]
indeed. the example was made before they changed their api. here is a new domain: https://mobileapi.toshibahomeaccontrols.com/

you may also try the examples from https://github.com/KaSroka/Toshiba-AC-control
there an updated api version should be used.

**Comment by runbert** [comment]
Thanks! Got that one working with the GUI.

Is there any chance you could provide a small code snippet for setting ON/OFF status from command line using that API (https://github.com/KaSroka/Toshiba-AC-control) without the need of using a GUI?

For instance: `py toshiba_ac.py --user USERNAME --pass PASS --status ON/OFF`

Really new to python, so that would be really helpful.

Thanks alot,

**Comment by runbert** [comment]
Managed to solve it.

Closing ticket.
