### ISSUE TITLE
Feature: provide more informations from the api as entity attributes

### ISSUE THREAD

**Issue by h4de5** [h4de5/home-assistant-toshiba_ac#9]
The climate shows the following attributes at the moment:

```
hvac_modes:
  - auto
  - heat
  - cool
  - 'off'
  - dry
  - fan_only
min_temp: 17
max_temp: 30
target_temp_step: 1
fan_modes:
  - auto
  - quiet
  - low
  - medium_low
  - medium
  - medium_high
  - high
preset_modes:
  - low_power
  - mid_power
  - high_power
swing_modes:
  - vertical
  - 'off'
current_temperature: 27
temperature: 22
fan_mode: quiet
hvac_action: 'off'
preset_mode: null
swing_mode: 'off'
friendly_name: Klima
supported_features: 57
```

some more informations could be useful to know. e.g.:

- ac_outdoor_temperature
- ac_self_cleaning
- ac_air_pure_ion
- ac_merit_a_feature
- ac_merit_b_feature
- device_id
- ac_id
- ac_unique_id

**Comment by h4de5** [comment]
i see. in this case its a lot less useful :( but it may still help with some automations.
i'll add it to the attributes for now at least.

**Comment by h4de5** [comment]
what else I hope we can find out:
- does the device the external silent mode?
- does the device support energy consumption monitoring?
- which firmware version is currently installed?
- maybe: get the model number, for proper comparing and debugging

**Comment by KaSroka** [comment]
I think that last two may be added easily in toshiba-ac. For the first one I have to investigate this. For second I may need your help to see if your mobile app makes request for energy consumption of it's notified somehow earlier that device doesn't support it.

**Comment by KaSroka** [comment]
@h4de5 can you check toshiba-ac logs and let me know what you have set for `'MeritFeature'`? Mine looks like this: `'MeritFeature': '7c03'`. I'm writing a decoder for this but I want to cross check if this works as expected.

**Comment by h4de5** [comment]
how can I get a read from that?

**Comment by KaSroka** [comment]
It's in the debug logs, you have to enable them for toshiba-ac in HA configuration.

**Comment by h4de5** [comment]
it seems my device does not support anything :(

can I get access properties for: **ACModelId, FirmwareVersion** and in case it delivers something readable for your device: **Description**

```json
{
   "ResObj":[
      {
         "GroupId":"7xx8",
         "GroupName":"All",
         "ConsumerId":"5xx3",
         "TimeZone":"W. Europe Standard Time",
         "ACList":[
            {
               "Id":"5xx1",
               "DeviceUniqueId":"4xxx8",
               "Name":"Klima",
               "ACModelId":"1",
               "Description":"AC_xx8",
               "CreatedDate":"4/30/2019 12:02:36 PM",
               "ACStateData":"3142174131640f101a7ffe0b00001002010000",
               "FirmwareUpgradeStatus":"",
               "URL":"",
               "File":"",
               "MeritFeature":"0000",
               "AdapterType":"0",
               "FirmwareVersion":"3.2.01",
               "FirmwareCode":"0000",
               "ModeValues":[
                  {
                     "Mode":"41",
                     "Temp":"16",
                     "FanSpeed":"41"
                  },
                  {
                     "Mode":"42",
                     "Temp":"17",
                     "FanSpeed":"41"
                  },
                  {
                     "Mode":"43",
                     "Temp":"18",
                     "FanSpeed":"36"
                  },
                  {
                     "Mode":"44",
                     "Temp":"16",
                     "FanSpeed":"41"
                  },
                  {
                     "Mode":"45",
                     "Temp":"16",
                     "FanSpeed":"36"
                  }
               ],
               "Control":"None"
            }
         ]
      }
   ],
   "IsSuccess":true,
   "Message":"Success",
   "StatusCode":"Success"
}

```

**Comment by KaSroka** [comment]
I have added decoding of `MeritFeature` (experimental)

I have updated toshiba-ac to 0.1.10, beside making sure that energy is fetched before returning list of devices this version also adds some new properties to ToshibaAcDevice:
`supported_merit_a_features` - list of supported merit A features, available from beginning 
`supported_merit_b_features` - list of supported merit B features, available from beginning 
`is_pure_ion_supported` - bool indication if Pure ION feature is supported, available from beginning 
`firmware_version` - version of the firmware, available from beginning 
`cdu` - model of CDU unit, available after some time as it's fetched in the background. Notified by `on_state_changed_callback`
`fcu` - model of FCU unit, afailable after some time as it's fetched in the background. Notified by `on_state_changed_callback`

**Comment by KaSroka** [comment]
```{
    "ResObj": [
        {
            "GroupId": "...",
            "GroupName": "All",
            "ConsumerId": "...",
            "TimeZone": "Central European Standard Time",
            "ACList": [
                {
                    "Id": "...",
                    "DeviceUniqueId": "...",
                    "Name": "Salon",
                    "ACModelId": "3",
                    "Description": "AC_<DEVICE_UNIQUE_ID>",
                    "CreatedDate": "8/4/2021 10: 43: 42 AM",
                    "ACStateData": "3145154131643010197ffe0b00001002000000",
                    "FirmwareUpgradeStatus": "",
                    "URL": "",
                    "File": "",
                    "MeritFeature": "7c03",
                    "AdapterType": "1",
                    "FirmwareVersion": "1.7.01",
                    "FirmwareCode": "0001",
                    "ModeValues": [
                        {
                            "Mode": "41",
                            "Temp": "19",
                            "FanSpeed": "41"
                        },
                        {
                            "Mode": "42",
                            "Temp": "19",
                            "FanSpeed": "33"
                        },
                        {
                            "Mode": "43",
                            "Temp": "15",
                            "FanSpeed": "41"
                        },
                        {
                            "Mode": "44",
                            "Temp": "19",
                            "FanSpeed": "41"
                        },
                        {
                            "Mode": "45",
                            "Temp": "15",
                            "FanSpeed": "41"
                        }
                    ],
                    "Control": None
                }
            ]
        }
    ],
    "IsSuccess": True,
    "Message": "Success",
    "StatusCode": "Success"
}

**Comment by KaSroka** [comment]
For the `MeritFeature` decoder - it's experimental as I have found only what it seems a part of it in dll files.
If someone has some more info how to decode it, please share it with me.

**Comment by operinko** [comment]
> The only problem (at least with my unit) is that when AC is off it reports unknown outdoor temperature.

I've got two units that are wired a bit differently.
Case 1: The old "recommended" method of mains power to indoor unit, split off to outdoor unit.
  - This method, outdoor temperature shows unknown when AC is off (indoor unit not powered, outdoor unit shuts down completely).  

Case 2: The new "recommended" method of mains power to outdoor unit, indoor unit powered through that.
  - This method, outdoor temperature keeps updating even if AC is off.

**Comment by KaSroka** [comment]
I have mains power connected to outdoor unit and from that to indoor unit (Case 2). Still when turned off I got a report that outdoor unit temperature is unknown.

**Comment by operinko** [comment]
Huh, I've just noticed something weird with my devices.
Having not opened the Toshiba App for a couple of weeks, I noticed that the values in HA stopped updating. HA can still push new values through and the device reacts accordingly, but the device doesn't seem to report updated indoor/outdoor values unless I open the toshiba app for a bit.

**Comment by tetienne** [comment]
FYI HA core team try to move away attribute and instead ask for entity instead even if it's a static value. Of course the entity should have a real meaning for the end user.
Such entities can be marked as diagnostic.

**Comment by h4de5** [comment]
also done
