### ISSUE TITLE
Toshiba API Server Issues?

### ISSUE THREAD

**Issue by florianbrede-ayet** [h4de5/home-assistant-toshiba_ac#92]
Hi,
sorry for the off-topic issue but discussions are not enabled for this repo and  I couldn't find a different place to ask:
*Does anyone else have issues with the API at the moment or had issues in the past?*

The API endpoints (and mobile app as well) started reporting incorrect states (does not affect the actual state of the units) for my indoor units 2 days ago:
```
No1 still shows the correct state
No2 resets the lever / swing mode regularly in the responses
No3 turns "off" randomly
No4 changes its set temperature randomly
```

Additionally, the reported outdoor unit temperatures are cycling in a random way that makes one think historic, cached values are being returned.

**Comment by dario-brombal** [comment]
Same for me, but also Toshiba app has problems and this morning showed me a message regarding cloud servers problems. Almost sure problems aren't related to homeassistant or this component.

**Comment by florianbrede-ayet** [comment]
Thanks for the feedback, I figured that it wasn't a fault of this component, because I also queried the Toshiba API directly with the same results.
I was just worried my WIFI dongles might be freaking out, but Toshiba at least was nice enough to put up the folowing message in the app now (as you mentioned):

![image](https://user-images.githubusercontent.com/48515354/201518477-563dadac-306e-4df2-b53a-ed14ec52ffa3.png)
