### ISSUE TITLE
hvac_action removed?

### ISSUE THREAD

**Issue by SketchCND** [h4de5/home-assistant-toshiba_ac#95]
Upgraded to 2022.11.0 and `hvac_action` attribute is missing.

Is there a particular reason for this that I may have missed or is it meant to be removed from current release?  I was making use of the attribut in my HA instance and hence have noticed it missing

**Comment by tetienne** [comment]
Hi,

This information was removed few releases ago.

Indeed, the information was not accurate and was just based on comparing the current temperature with the target temperature which is not enough and not allowed by Home Assistant Core team. 

The information must be returned by the device itself and not compute.
