### ISSUE TITLE
inverter data

### ISSUE THREAD

**Issue by cmderks93** [h4de5/home-assistant-toshiba_ac#96]
Im curious if its possible to get some extra data from the ac unit. 
for example: Fan speed, inverter frequency, defrost info, and so on. 

Thanks!

**Comment by h4de5** [comment]
please see if the underlying python package supports this:

**Comment by cmderks93** [comment]
I've installed the package and opened it with pip. 
I'm getting some info. 

toshiba_ac.device: [AC_XXXXXXXX] AC heartbeat from AMQP: {'iTemp': 21, 'oTemp': 5, 'fcuTcTemp': 44, 'fcuTcjTemp': 36, 'fcuFanRpm': 69, 'cduTdTemp': 87, 'cduTsTemp': 4, 'cduTeTemp': 3, 'cduCompHz': 62, 'cduFanRpm': 78, 'cduPmvPulse': 35, 'cduIac': 1}

**Comment by tetienne** [comment]
That's interesting! We can create sensor based on this fan speed.

Can you share your Python script please?

**Comment by cmderks93** [comment]
It's just the example from KaSroka's library.
