### ISSUE TITLE
Missing unit of temperature

### ISSUE THREAD

**Issue by maarten117** [h4de5/home-assistant-toshiba_ac#97]
Please tell me what I missed. 

Logger: homeassistant.setup
Source: setup.py:320 
First occurred: 11:10:34 (1 occurrences) 
Last logged: 11:10:34

Unable to prepare setup for platform toshiba_ac.climate: Platform not found (cannot import name 'UnitOfTemperature' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

**Comment by tetienne** [comment]
Hi,

What’s your HA version? The minimum requirement is 2022.5.0.
