### ISSUE TITLE
Issue after upgrading to 2022.12.0

### ISSUE THREAD

**Issue by odechr** [h4de5/home-assistant-toshiba_ac#99]
Logger: homeassistant.setup
Source: setup.py:202
First occurred: 22:38:41 (1 occurrences)
Last logged: 22:38:41

Setup failed for custom integration toshiba_ac: Requirements for toshiba_ac not found: ['toshiba-ac==0.3.0'].

Log Details (ERROR)

Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 22:37:51 (3 occurrences)
Last logged: 22:38:41

Unable to install package toshiba-ac==0.3.0: ERROR: Cannot install toshiba-ac==0.3.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by notexa** [comment]
I just upgraded to 2022.12.0 and now the integration isn't working for me as weel.

I get the following notification now: 
```
2022-12-08 01:09:20.267 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration toshiba_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-08 01:10:01.019 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration toshiba_ac: Requirements for toshiba_ac not found: ['toshiba-ac==0.3.0'].
homeassistant.requirements.RequirementsNotFound: Requirements for toshiba_ac not found: ['toshiba-ac==0.3.0'].
```

**Comment by h4de5** [comment]
0.3.0 of toshiba didn't change.
 maybe HA is finally checking for dependicies for sub-depending packages, therefor solving the requests v1 vs v2 issues.
in this case this may fix it - but we need to wait for a release:
https://github.com/KaSroka/Toshiba-AC-control/pull/35

**Comment by operinko** [comment]
Until Toshiba-AC-control is fixed, I'm running a modified version of this integration, by temporarily changing the manifest.json in custom_components/toshiba_ac.
Change line 8 from:
`"toshiba-ac==0.3.0"`
to
`"git+https://github.com/operinko/Toshiba-AC-control@899c268#toshiba-ac"`
and restart HA. This makes the integration require my already-patched AC-control fork.

**Comment by notexa** [comment]
Thanks for the temp fix @operinko

**Comment by Snapperud** [comment]
Confirm, worked like a charm here to :-) Thanks

**Comment by anto294** [comment]
> Until Toshiba-AC-control is fixed, I'm running a modified version of this integration, by temporarily changing the manifest.json in custom_components/toshiba_ac.
> Change line 8 from:
> `"toshiba-ac==0.3.0"`
> to
> `"git+https://github.com/operinko/Toshiba-AC-control@899c268#toshiba-ac"`
> and restart HA. This makes the integration require my already-patched AC-control fork.

Error “{"message":"Invalid handler specified"}” if I try to add again Toshiba Device. 

Probably the pull link is broken

**Comment by 46lupo** [comment]
Can confirm! That "work around" worked like  a charm. Thank you so much, great work! 
Thanks, Matt

**Comment by HeroBart** [comment]
> 0.3.0 of toshiba didn't change. maybe HA is finally checking for dependicies for sub-depending packages, therefor solving the requests v1 vs v2 issues. in this case this may fix it - but we need to wait for a release: [KaSroka/Toshiba-AC-control#35](https://github.com/KaSroka/Toshiba-AC-control/pull/35)

The workaround works fine, but unfortunately it didn't fix the "requests" problem :)
Still very happy with this plugin!

**Comment by bjoove** [comment]
I tried the @operinko work around but getting this issue instead.. Any clues? 
Does this work around require anything else on the HA server? (like @operinko "Toshiba-AC-control" integration?)

Logger: homeassistant.config_entries
Source: config_entries.py:355
First occurred: 21:46:02 (1 occurrences)
Last logged: 21:46:02

Error importing platform config_flow from integration toshiba_ac to set up toshiba_ac configuration entry: No module named 'toshiba_ac.utils'

**Comment by operinko** [comment]
Nope, the workaround (by editing the manifest.json file) should be all that's needed.

**Comment by jimmycr** [comment]
> Nope, the workaround (by editing the manifest.json file) should be all that's needed.

I can confirm, everything works for me after applying workaround.

**Comment by gmarongiu71** [comment]
With the new update, 2022.12.3, rework with original solution:
"toshiba-ac==0.3.0"

**Comment by odechr** [comment]
Yes i had to revert back to the original string "toshiba-ac==0.3.0" too.
Guess i can close this.

**Comment by h4de5** [comment]
as listed in the changelogs from HA they are planning to revisit tgis upgrade later again when they sorted out some other side effects. so this may come up in future HA releases again.

**Comment by operinko** [comment]
Poking my head into a closed issue, but:
Latest HA beta has bumped aiohttp to 3.8.4, which means toshiba-ac will break again :D
